### ISSUE TITLE
Caps lock key does not work in BasiliskII and SheepShaver for OSX/macOS

### ISSUE THREAD

**Issue by RonaldPR** [kanjitalk755/macemu#101]
The issue was found with recent universal builds on macOS 11 (Big Sur) on both Intel and Apple Silicon, regardless whether a keycodes file is used.

I cannot test Intel-only versions of BasiliskII on my M1 Mac, but Intel-only SheepShaver builds will run with Rosetta. It appears that the caps lock key works fine in my 4 December 2019 through 22 September 2020 builds, but stopped working in my 2 February 2021 and later builds.

**Comment by kanjitalk755** [comment]
It turns out that in SDL 2.0.14, the behavior of caps lock key has changed.
(It has reverted to the same behavior as up to SDL 2.0.9)

Fixed.

**Comment by RonaldPR** [comment]
So, there goes the fix for SDL 2.0.10. :)

I will post new builds on emaculation forum soon.
