### ISSUE TITLE
Copying images from guest to host does not work in SheepShaver

### ISSUE THREAD

**Issue by RonaldPR** [kanjitalk755/macemu#102]
Copying images from guest to host does not work in SheepShaver, at least not in macOS 11 (Big Sur).

It used to work in 32-bit builds from cebix/macemu, was broken in 64-bit builds, but was fixed between 11 February 2012 and 15 July 2012. I cannot run these older builds in Big Sur.

In macOS 11 (Big Sur) it does not work in any of my builds from this fork (since 11 July 2018). I do not remember trying to copy images from guest to host in many years, so I cannot be sure it also did not work before in previous OSX/macOS versions.

See also discussion here: https://www.emaculation.com/forum/viewtopic.php?f=20&t=11314

**Comment by kanjitalk755** [comment]
I just tried it and it worked on High Sierra but not on Big Sur.
Big Sur doesn't seem to support pasting PICT from the clipboard anymore.

**Comment by RonaldPR** [comment]
That makes sense. Apple stopped support for the PICT format (probably with macOS 10.15, Catalina). PICT images cannot be opened in Big Sur, not even by an app like Graphic Converter.

And copying images in Mac OS 9 puts PICT on the clipboard.

**Comment by RonaldPR** [comment]
Interestingly, PICT images can be opened by LibreOffice, also in Big Sur.
But copying an image in SheepShaver and pasting in LibreOffice does not work.

**Comment by kanjitalk755** [comment]
Support for PICT on macOS has been phased out.
For example, QuickTime-compressed PICT couldn't be drawn before Big Sur.
It seems that "paste" is no longer possible this time.

**Comment by emendelson** [comment]
Also, Big Sur's AppleScript can read a PICT image file Into the Big Sur clipboard. The image gets converted into TIFF format. I've been trying to find a way - in SheepShaver - to save an image in the clipboard to a file in PICT format, but it doesn't work (at least not under Mac OS 9). I don't know if that's a SheepShaver problem or an OS 9 problem.

**Comment by kanjitalk755** [comment]
> I've been trying to find a way - in SheepShaver - to save an image in the clipboard to a file in PICT format, but it doesn't work (at least not under Mac OS 9).

For example, you can do it with GraphicConverter.
I think GraphicConverter supports AppleScript.

**Comment by emendelson** [comment]
Yes, GraphicConverter does this job, and I've created an AppleScript to do it. It would be good to be able to do this entirely from AppleScript, and avoid opening the GraphicConverter window, but that may be impossible. Thank you again!
