### ISSUE TITLE
Crashing when scanning certain Japanese CD-ROMs

### ISSUE THREAD

**Issue by gingerbeardman** [kanjitalk755/macemu#103]
Hi,

I have a lot of old Japanese CD-ROM MACLIFE from 1997 to 1999.

I use [DiskTracker 2.02](https://macintoshgarden.org/apps/disktracker-202) to catalogue the contents.

With two specific discs, the scan results in a hard crash of BasiliskII.
With all the previous discs, scanning works without issue.

How can I see if this is an emulator problem (my hunch) or an app problem?

I have given a lot of memory to BasiliskII (from 32MB up to 128MB) and to the app (from 4MB up to 64MB).

I'm happy to provide one or both CD-ROM ISO if they would be helpful.

Crash logs: [BasiliskII_2021-08-24-crashes.zip](https://github.com/kanjitalk755/macemu/files/7035530/BasiliskII_2021-08-24-crashes.zip)

**Comment by kanjitalk755** [comment]
I'll check with the debugger, so please provide the ISO files.
Also, please tell me the operation procedure of DiskTracker that causes a crash.

**Comment by gingerbeardman** [comment]
DiskTracker 2.02
1. File > New Catalog
2. Scan > Scan Mounted Volume
3. Choose "CD-ROM MACLIFE 130" > Scan
4. Scan begins (Hard Crash)

Screen recording: https://imgur.com/a/Kc9gymp

**Comment by gingerbeardman** [comment]
Crashing ISO: https://archive.org/details/cd-rom-maclife-130

Working ISO: https://archive.org/details/cd-rom-maclife-31

**Comment by kanjitalk755** [comment]
An unrecoverable SEGV occurred while scanning MACLIFE130.
However, SheepShaver was able to scan successfully.
There is a alternative, so I won't investigate further.

**Comment by kanjitalk755** [comment]
The long name of SEGV is "Segmentation fault".

https://en.wikipedia.org/wiki/Segmentation_fault

In this issue, the actual 68k Mac may also behave in the same way, or the BasiliskII emulation may be incomplete.

**Comment by gingerbeardman** [comment]
Thanks, I finished the cataloguing using SheepShaver. 😎
