### ISSUE TITLE
Restart with CD-ROM mounted results in prompt to initialise disk

### ISSUE THREAD

**Issue by gingerbeardman** [kanjitalk755/macemu#105]
Steps to reproduce
1. in prefs file: `cdrom /Disk/Folder/HFS.iso`
2. Start BasiliskII
3. CD-ROM is mounted on Desktop 
4. Special > Restart
5. wait for restart to complete

Expected
- CD-ROM should still be mounted after restart

Actual
- CD-ROM is not mounted after restart, instead there's a prompt to initialise disc

> <img width="374" alt="Screen shot 2021-08-30 at 11 50 26" src="https://user-images.githubusercontent.com/49612/131328451-4a25b366-8e90-476e-914c-897d89e9e6b9.png">

Workaround
- mount CD-ROM as `disk`, rather than `cdrom`, but this is not ideal for many reasons.

**Comment by RonaldPR** [comment]
This is a known issue (described in the Emaculation SheepShaver setup guide). A disk image that is mounted as CD-ROM cannot be removed within SheepShaver. It will stay as an unreadable Audio CD. Restarting will unmount and remount the volumes. Always only add and remove CD-ROM images in the volumes list in Preferences.

The best workaround is to not restart the emulated machine, but to quit SheepShaver and launch it again.
(In fact, it is better to never restart the emulator, but instead always shut down and start again.)

**Comment by kanjitalk755** [comment]
Fixed.

**Comment by gingerbeardman** [comment]
@RonaldPR this issue is regarding BasiliskII, not SheepShaver.

@kanjitalk755 thanks!
