### ISSUE TITLE
"ERROR: Not enough free memory." when launching BasiliskII on Fedora 34

### ISSUE THREAD

**Issue by oaguy1** [kanjitalk755/macemu#106]
Hello! I am trying to build BasiliskII on my Fedora 34 workstation. I have been able to build it according to the build in the instructions in the README.md. When I launch the program, I get the following output:

```
$ ./BasiliskII 
Basilisk II V1.1 by Christian Bauer et al.
WARNING: Unknown preferences keyword 'sdl_vsync'
ERROR: Not enough free memory.
Segmentation fault (core dumped)

```

Do you have any idea what might be causing this? I am happy to run any debugging steps to provide more information.

I have attached the general specs of my machine from the neofetch output below:

```
$ neofetch 
          /:-------------:\          lilyhughes-robinson@lillilegion.localdomain 
       :-------------------::        ------------------------------------------- 
     :-----------/shhOHbmp---:\      OS: Fedora 34 (Workstation Edition) x86_64 
   /-----------omMMMNNNMMD  ---:     Host: 82B1 Lenovo Legion 5 15ARH05H 
  :-----------sMMMMNMNMP.    ---:    Kernel: 5.13.12-200.fc34.x86_64 
 :-----------:MMMdP-------    ---\   Uptime: 3 days, 10 hours, 45 mins 
,------------:MMMd--------    ---:   Packages: 2784 (rpm), 37 (flatpak) 
:------------:MMMd-------    .---:   Shell: bash 5.1.0 
:----    oNMMMMMMMMMNho     .----:   Resolution: 1920x1080, 1920x1080 
:--     .+shhhMMMmhhy++   .------/   DE: GNOME 40.4 
:-    -------:MMMd--------------:    WM: Mutter 
:-   --------/MMMd-------------;     WM Theme: Adwaita 
:-    ------/hMMMy------------:      Theme: Adwaita-dark [GTK2/3] 
:-- :dMNdhhdNMMNo------------;       Icons: Adwaita [GTK2/3] 
:---:sdNMMMMNds:------------:        Terminal: gnome-terminal 
:------:://:-------------::          CPU: AMD Ryzen 7 4800H with Radeon Graphics (16) @ 2.900GHz 
:---------------------://            GPU: NVIDIA GeForce GTX 1660 Ti Mobile 
                                     Memory: 7395MiB / 63667MiB
```

**Comment by kanjitalk755** [comment]
Try setting the ramsize in the ~/.basilisk_ii_prefs to:
```
ramsize 32
```

**Comment by oaguy1** [comment]
I feel so silly, the ramsize in my ~/.basilisk_ii_prefs was set to some absurdly high number. Perhaps an older version of BasiliskII stored the ramsize in bytes. Setting it to 32 made it launch perfectly, thank you.

**Comment by oaguy1** [comment]
The other version I've been using is the flatpak. It actually gave me some trouble after modifying the ramsize value to 32. Maybe the flatpak and the source version use different units for the ram in ~/.basilisk_ii_prefs

**Comment by oaguy1** [comment]
This is definitely true. When I opened the flatpack version and changed the ramsize to 32, it updated my ~/.basilisk_ii_prefs to make ramsize 33554432

**Comment by oaguy1** [comment]
![Screenshot from 2021-09-03 10-12-59](https://user-images.githubusercontent.com/2355614/132019570-f6589839-7e52-4eae-aabf-eebabe40ee29.png)

This is taken from my source built Basilisk binary after adjusting the ram in the flatpak

**Comment by kanjitalk755** [comment]
In this fork, if the ramsize is 1000 or less, it is considered in megabytes, otherwise bytes.
Therefore, `ramsize 32` and `ramsize 33554432` are equivalent.
