### ISSUE TITLE
Slow dissolve transition effect

### ISSUE THREAD

**Issue by gingerbeardman** [kanjitalk755/macemu#107]
I'm wondering why under BasiliskII the dissolve transition effect is so slow?

It's visible in many HyperCard stacks. Here's one: 
https://archive.org/download/hypercard_zizi-vol-1/disk.img

Taken from: https://archive.org/details/hypercard_zizi-vol-1

I've tried the following, with no change
- different screen settings
- different colour depths
- different ROMs

## Comparison

- Mini Mac it's fast
- Web emulator (based on Mini vMac) it is also fast
- BasiliskII it's very slow (almost 20x slower)

## Screen recordings

- Mini vMac (1 second)

https://user-images.githubusercontent.com/49612/137552194-23180566-2fdc-4b0c-a1ff-cfda3eba0903.mov

---- 

- Mini Mac Web (1 second)

https://user-images.githubusercontent.com/49612/137552215-e0ceef7c-f5e1-4f46-af9c-411e7b0c0050.mov

---- 

- BasiliskII (~18 seconds!)

https://user-images.githubusercontent.com/49612/137552271-013c83d6-140b-41b0-8992-2a4934d41f75.mov

### My setup
- BasiliskII latest from emaculation
- Quadra650 rom
- System 7.5.3 (both English and Japanese)

**Comment by gingerbeardman** [comment]
It's also reported here:
- https://www.emaculation.com/forum/viewtopic.php?t=8264 (BasiliskII)

Also related
- https://www.emaculation.com/forum/viewtopic.php?t=7376 (Sheepshaver)

**Comment by kanjitalk755** [comment]
CPU usage is stuck at 100% during the transition.
I checked the time profile, it resulted as follows.

![ss_timeprofile](https://user-images.githubusercontent.com/33744007/137573219-fe2556dd-ec5f-4632-a970-c4a2e6a3eedc.png)

Much time is spent on the CPU emulation.
Since it is difficult to investigate and correct the cause inside the UAE CPU core, use SheepShaver as an alternative.

**Comment by kanjitalk755** [comment]
It turned out that Basilisk II needed a high-precision timer, which is implemented only in SheepShaver.
I backported it to Basilisk II.

**Comment by gingerbeardman** [comment]
Amazing, this is huge news for me. Thank you so much! 

I'm off to build the latest code right now.

**Comment by 19eighties** [comment]
@gingerbeardman Just wanted to shout out that you are my hero for getting the ball rolling on this fix and also @kanjitalk755  for implementing it. This has been an issue for me for probably over a decade.

**Comment by gingerbeardman** [comment]
@19eighties no worries! it really was worth it.
