### ISSUE TITLE
Support for RAW (2352 byte) Mode 1 BIN/CUE

### ISSUE THREAD

**Issue by gingerbeardman** [kanjitalk755/macemu#108]
Often CDs are dumped as RAW (2352 byte) BIN/CUE to include hidden data not covered by regular BIN/CUE or ISO. 

This RAW BIN/CUE is not currently supported by BasiliskII.

I have to rip CD twice: first as ISO to use with BasiliskII, and second as RAW BIN/CUE for my archive. 

So I did some googling and found this old chat from 2010 about adding support for this type of CD disc image. It includes code. 

https://sourceforge.net/p/basilisk/mailman/basilisk-devel/thread/AANLkTim9MBjJ0%2BfaNP2RoPsf6wqih3Li8V-WBnaXjXa1%40mail.gmail.com/

Any thoughts? Thank you

**Comment by kanjitalk755** [comment]
> https://sourceforge.net/p/basilisk/mailman/basilisk-devel/thread/AANLkTim9MBjJ0%2BfaNP2RoPsf6wqih3Li8V-WBnaXjXa1%40mail.gmail.com/

The above feature is included in current BasiliskII.
If the RAW BIN/CUE is general data (Mode 1), BasiliskII needs to perform error correction and there is no plan to support this.

**Comment by gingerbeardman** [comment]
Ah, OK. The discs are indeed Mode 1.
