### ISSUE TITLE
macOS BasiliskII universal builds crash on Intel

### ISSUE THREAD

**Issue by RonaldPR** [kanjitalk755/macemu#109]
I noticed before that I could not run my BasiliskII universal builds with Rosetta on my M1 iMac, unlike my SheepShaver builds that run fine with Rosetta.

Several users reported that my BasiliskII universal builds crash on Intel.

See also here on cebix/macemu: https://github.com/cebix/macemu/issues/251 (about my build from kanjitalk755/macemu)

I created a new build just now and again in crashes when I try to run it with Rosetta.

**Comment by kanjitalk755** [comment]
The BasiliskII emulation core, UAE CPU, does not work with Rosetta 2.
> Several users reported that my BasiliskII universal builds crash on Intel.

There was no such report until Big Sur, so the cause may be Monterey.

It works stably on High Sierra.
My Intel machine doesn't support newer macOS, so I can't verify it.

**Comment by kanjitalk755** [comment]
I found BasiliskII runs with Rosetta if excluding JIT compiler at build time.
Try:
https://github.com/kanjitalk755/macemu/tree/no_jit

**Comment by RonaldPR** [comment]
Maybe it will also not crash on Intel with recent macOS versions. I do not have an Intel Mac anymore, but I will open a topic in Emaculation forum to ask for testing on Intel machines with recent macOS versions.

**Comment by RonaldPR** [comment]
Only two reports, one reports a different issue and the other reports no issues. Not sufficient to draw any conclusions. Apparently some (few?) have issues with universal BasiliskII builds in recent macOS on Intel, but others (most?) have not. 

Maybe useful to keep the no-jit version for those who want or need, for whatever reason, to run BasiliskII with Rosetta2 on Apple Silicon?

**Comment by kanjitalk755** [comment]
Do you plan to release both versions (jit and no-jit) everytime?
Otherwise, I will keep `no-jit` branch but will not merge it with the latest.

**Comment by RonaldPR** [comment]
No, I do not plan to release both versions each time. I meant that it could be useful to keep the `no-jit` branch in case someone would ask for a possibility to run BasiliskII with Rosetta2 on Apple Silicon.
