### ISSUE TITLE
Forcing swap_opt_cmd to false if the keycodes file is valid can be removed

### ISSUE THREAD

**Issue by RonaldPR** [kanjitalk755/macemu#112]
The new `reservewindowskey` feature (plus correction) provides a huge improvement of the user experience on Windows.

All the forced workarounds in the keycodes files can now be removed.

The greatly simplified new keycodes files can be found here: http://ronaldpr.home.xs4all.nl/keycodes/Keycodes_January_2022.zip

Also the feature that forces `swap_opt_cmd` to false if the keycodes file is valid can now be removed. I think it should best be removed everywhere (macOS, Windows, Linux) to give the user freedom of choice of keyboard.

At the same time the default should best be (if not already so):
In macOS: `swap_opt_cmd false`
and in Windows and in Linux: `swap_opt_cmd true`

Can you make it so?

**Comment by kanjitalk755** [comment]
> Also the feature that forces `swap_opt_cmd` to false if the keycodes file is valid can now be removed. I think it should best be removed everywhere (macOS, Windows, Linux) to give the user freedom of choice of keyboard.

Removed.

> At the same time the default should best be (if not already so):
> In macOS: `swap_opt_cmd false`
> and in Windows and in Linux: `swap_opt_cmd true`

Those are already set as above.

**Comment by RonaldPR** [comment]
Thanks.
