### ISSUE TITLE
(Sheepshaver [potentially Basilisk too]) Arch Linux error at "make" step

### ISSUE THREAD

**Issue by AceSoren** [kanjitalk755/macemu#115]
Process:
1. clone macemu
2. go to SheepShaver
3. make links
4. go to /src/Unix
5. execute NO_CONFIGURE=1 ./autogen.sh
6. execute ./configure --enable-sdl-video=yes --enable-sdl-audio=yes --with-bincue
7. make (grinds to a screeching halt here)
8. strip SheepShaver (cannot do, step 7 is erroring out)

Error:
./sysdeps.h:32:2: error: #error "You don't have ANSI C header files"
 32 | #error "You don't have ANSI C header files"
      |

make: *** [Makefile:197: obj/main.o] Error 1

Installation: Arch Linux x64 fully updated as of yesterday before shutting down the laptop for the night.

**Comment by kanjitalk755** [comment]
I was able to build it on Debian, but it may fail depending on the distro.
Append `#define STDC_HEADERS 1` to SheepShaver/src/Unix/config.h.

**Comment by Dungeonseeker** [comment]
Add -DSTDC_HEADERS=1 to CXXFLAGS

**Comment by AceSoren** [comment]
Thank you both. I will give that a try when I get back on Arch. How I found out about this prob was a project, using Arch Linux to exclusively host SheepShaver on startup.

**Comment by kanjitalk755** [comment]
Removed the check for STDC_HEADERS.
