### ISSUE TITLE
Feature Request: CHD support for SS/BII

### ISSUE THREAD

**Issue by adespoton** [kanjitalk755/macemu#116]
Any chance of anyone adding native CHD image support to SS/BII?  It should be relatively easy, as the implementation code is already available for MESS/MAME and RetroArch, in a multi-platform manner.  Since chdman exists for all modern platforms, CHD images would be much easier to handle than DMGs.  Plus, they're both read/write and compressed :)

**Comment by adespoton** [comment]
Here's a link to a project that added CHD support to the Saturn emulator SSF: https://github.com/Slippy2k/CHDSSF/tree/master/ssf_patch

**Comment by adespoton** [comment]
...and another reason to add CHD support: I just realized that all my HFS sparsebundles are no longer sparse on macOS Monterey: with the removal of HFS as a native filesystem, the OS can no longer tell what is free space on the volume, and so can't shrink the volume size.  Running compact expands the images to their maximum size.

**Comment by kanjitalk755** [comment]
I don't plan to implement this feature.
Of course, a PR is welcome.

**Comment by MarcDoughty** [comment]
@adespoton , it looks like CHDs are mostly used for retro gaming ROMs; I don't think they'd be the right fit for a computer emulator, they're optimized for read-only use.

What I think fits better for this use case is qcow2, which is well documented, optimized for use with emulators, open source, and interoperable with the QEMU emulator (which is closing in on solid Mac68k and MacPPC support).

@kanjitalk755 , I don't have the skills or the time to figure that out, but I'd be happy to sponsor or offer bounties for a few feature modernization efforts. Would you be interested in that sort of thing?

**Comment by kanjitalk755** [comment]
I maintain BII and SS for free based on my interests.
And I'm not interested in adding other disk image formats to them.

**Comment by MarcDoughty** [comment]
Thanks @kanjitalk755 , Would disk-image-related PRs on this project be appropriate if someone else does the relevant work? Asking so the question is answered for anyone curious in the future.

**Comment by kanjitalk755** [comment]
Yes, the PRs are welcome.
