### ISSUE TITLE
[Basilisk II] Ability to run CPUs emulation at roughly native speed

### ISSUE THREAD

**Issue by vashpan** [kanjitalk755/macemu#117]
Originally (from what I understand) Basilisk II was built in the times where classic MacOS was still a very alive product, with CPUs 10s or maybe even 100s times slower than today, and having the fastest possible emulation was one of the main goals. But we're way past of having any trouble in emulating 68k CPUs, and now the opposite is the problem. Emulation often runs WAY too fast, even without JIT.

This may also pose problem with emulation, as some apps may work incorrectly at those insane speeds.

It would be handy to have a flag that would limit CPU speed to more real values. It doesn't have to be accurate, but a rough estimation, depending on emulated CPU type and clock speed.

I know UAE core is able to support this, so maybe it won't be so hard to add, as a simple flag in settings file.

**Comment by kanjitalk755** [comment]
Try:

https://github.com/kanjitalk755/macemu/tree/test_delay

Append prefs file to:

`delay 1000`

The value is the extra delay (micro seconds) every 64k instructions.

**Comment by vashpan** [comment]
Thank you for that 🙂 I just tested it, and it seems to work as expected 👍

Although for sure a "proper" limiter would be nice as well, depending on CPU model and speed. I may try to experiment with that.

**Comment by kanjitalk755** [comment]
Merged to the master.

**Comment by RonaldPR** [comment]
Does this work for BasiliskII only or also for SheepShaver?

**Comment by kanjitalk755** [comment]
BasiliskII only.
This feature will slow down the maximum speed slightly and will not be implemented in SheepShaver unless requested.
