### ISSUE TITLE
Incorrect configure output and broken build with libvhd enabled

### ISSUE THREAD

**Issue by MarcDoughty** [kanjitalk755/macemu#124]
Host: Ubuntu 22.04 arm64

Configure and build with no options works great:

> Mac OS X GUI ........................... : no
> Mac OS X Sound ......................... : no
> SDL support ............................ : video audio
> SDL major-version ...................... : 2
> BINCUE support ......................... : no
> **LIBVHD support ......................... : no**
> VDE support ............................ : no
> XFree86 DGA support .................... : no
> XFree86 VidMode support ................ : no
> fbdev DGA support ...................... : no
> Enable video on SEGV signals ........... : yes
> ESD sound support ...................... : no
> GTK user interface ..................... : gtk2
> mon debugger support ................... : no
> Running m68k code natively ............. : no
> **Use JIT compiler ....................... : no**
> JIT debug mode ......................... : no
> Floating-Point emulation core .......... : IEEE fpu core
> Assembly optimizations ................. : none
> **Addressing mode ........................ : direct**
> Bad memory access recovery type ........ : siginfo

When I try to configure BasiliskII with '--with-libvhd', the configuration fails saying that "the JIT Compiler requires Direct Addressing".

When I try to work around that by explicitly disabling the JIT compiler, I get more strangeness (GTK dropped, addressing mode changed):

> Basilisk II configuration summary:
> 
> Mac OS X GUI ........................... : no
> Mac OS X Sound ......................... : no
> SDL support ............................ : video audio
> SDL major-version ...................... : 2
> BINCUE support ......................... : no
> **LIBVHD support ......................... : yes**
> VDE support ............................ : no
> XFree86 DGA support .................... : no
> XFree86 VidMode support ................ : no
> fbdev DGA support ...................... : no
> Enable video on SEGV signals ........... : no
> ESD sound support ...................... : no
> **GTK user interface ..................... : no**
> mon debugger support ................... : no
> Running m68k code natively ............. : no
> Use JIT compiler ....................... : no
> JIT debug mode ......................... : no
> Floating-Point emulation core .......... : IEEE fpu core
> Assembly optimizations ................. : none
> **Addressing mode ........................ : memory banks**
> Bad memory access recovery type ........ :
>

**Comment by kanjitalk755** [comment]
I tried this on Debian and got the same result.

In `config.log`:
```
configure:7318: gcc -o conftest -g -O2 -D_REENTRANT -I/usr/include/SDL2  -DHAVE_LIBVHD  conftest.c -lvhd  -lm -lrt -lrt  -lSDL2 -lvhd -luuid >&5
/usr/bin/ld: cannot find -lvhd
```
If you find a same error in your `config.log`, `libvhd` is not installed properly.
