### ISSUE TITLE
"You don't have ANSI C header files" - GCC 12.1

### ISSUE THREAD

**Issue by Ocawesome101** [kanjitalk755/macemu#130]
I'm running Arch Linux with GCC 12.1.  Trying to compile SheepShaver from commit `d7e93d8f3746b4803dd5c6521029ddbf28084844` results in an error from `sysdeps.h` that I don't have ANSI C headers.  I commented out the check (`sysdeps.h`, line 32) and the emulator compiles and runs fine.

**Comment by kanjitalk755** [comment]
Removed the check for STDC_HEADERS.
