### ISSUE TITLE
Linux builds prefs

### ISSUE THREAD

**Issue by cat7** [kanjitalk755/macemu#131]
Hi,

When testing the Linux apppimages builds for Basilisk and SheepShaver from https://github.com/Korkman/macemu-appimage-builder I noticed several issues with the prefs on Linux hosts when running the Basilisk and SheepShaver GUIs These also occur with my own Linux builds.

1. On Linux host a clean start without prior existing prefs of Basilisk oand SheepShaver create the sets of prefs pasted below.
On Linux Basilisk and SheepShaver are able to boot from a real cd, so by default there should be a pref like "cdrom /dev/cdrom" which now is absent.

2. When I manually edit the prefs and add an entry like "cdrom /home/cdimage.iso" Basilisk and SheepShaver will not boot from the iso.

This means there is no way of starting a clean installation from a real CD without manually editing the prefs for both. I can also not boot from a CD image.

3. In the SheepShaver Linux prefs ignoreillegal is set to false, while I believe it might be best set to true.
 
I hope you can take a look at these issues. 

Basilisk default prefs:

displaycolordepth 0
extfs /
seriala /dev/ttyS0
serialb /dev/ttyS1
udptunnel false
udpport 6066
bootdrive 0
bootdriver 0
ramsize 8388608
frameskip 6
modelid 5
cpu 3
fpu false
nocdrom false
nosound false
noclipconversion false
nogui false
jit false
jitfpu true
jitdebug false
jitcachesize 8192
jitlazyflush true
jitinline true
keyboardtype 5
keycodes false
mousewheelmode 1
mousewheellines 3
hotkey 0
scale_nearest false
scale_integer false
yearofs 0
dayofs 0
mag_rate 0
swap_opt_cmd true
ignoresegv true
sound_buffer 0
name_encoding 0
dsp /dev/dsp
mixer /dev/mixer
idlewait true

SheepShaver default prefs:

extfs /
windowmodes 0
screenmodes 0
seriala /dev/ttyS0
serialb /dev/ttyS1
bootdrive 0
bootdriver 0
ramsize 16777216
frameskip 8
gfxaccel true
nocdrom false
nonet false
nosound false
nogui false
noclipconversion false
ignoresegv true
ignoreillegal false
jit true
jit68k false
keyboardtype 5
hardcursor false
hotkey 0
scale_nearest false
scale_integer false
cpuclock 0
yearofs 0
dayofs 0
mag_rate 0
swap_opt_cmd true
sound_buffer 0
name_encoding 0
keycodes false
mousewheelmode 1
mousewheellines 3
dsp /dev/dsp
mixer /dev/mixer
idlewait true

**Comment by kanjitalk755** [comment]
> 1. On Linux host a clean start without prior existing prefs of Basilisk oand SheepShaver create the sets of prefs pasted below.
>    On Linux Basilisk and SheepShaver are able to boot from a real cd, so by default there should be a pref like "cdrom /dev/cdrom" which now is absent.

Fixed.

> 2. When I manually edit the prefs and add an entry like "cdrom /home/cdimage.iso" Basilisk and SheepShaver will not boot from the iso.

Not reproduced.
In Debian 11.3, both BII and SS could be booted from ISO images.

> 3. In the SheepShaver Linux prefs ignoreillegal is set to false, while I believe it might be best set to true.

Fixed.

**Comment by kanjitalk755** [comment]
I forgot that `cdrom` can have multiple entries.
Fixed.

**Comment by cat7** [comment]
Thanks, everything seems fine now.
