### ISSUE TITLE
Upload latest win builds pls

### ISSUE THREAD

**Issue by necros2k7** [kanjitalk755/macemu#135]
subj

**Comment by emendelson** [comment]
Visit emaculation.com for builds.

**Comment by kanjitalk755** [comment]
See #133.

**Comment by necros2k7** [comment]
That`s exactly the point - last commit was week ago - Sheepshaver build at site you proved is from January 2022. Maybe it would be good for community to setup Github Actions for recent builds?

**Comment by RonaldPR** [comment]
New builds are posted by me (macOS) and by Cat_7 (Windows) on Emaculation forum regularly and always when important fixes or important new features are available. Which commit after January 2022 is important to you now?

You can also create a new build yourself from the current source. Instructions are provided here.
