### ISSUE TITLE
segfault as root, "ERROR: Cannot map Low Memory Globals: Operation not permitted" as non-root user

### ISSUE THREAD

**Issue by stamasd** [kanjitalk755/macemu#141]
Built SheepShaver from the git sources on 9/11/2022, on Funtoo Linux (current, all updates). No build errors.

The resulting binary:
1. run as regular user, the GUI opens, options correctly set then when attempting to start I get error ERROR: Cannot map Low Memory Globals: Operation not permitted

2. Same but as root user:
sudo ./SheepShaver-kanjitalk
SheepShaver V2.5 by Christian Bauer and Mar"c" Hellwig
Reading ROM file...
WARNING: Cannot open /dev/cdrom (No such file or directory)
Using SDL/alsa audio output
Using SDL_Renderer driver: opengl
Detected CPU features: MMX SSE SSE2 SSE3 SSSE3
PowerPC CPU emulator by Gwenole Beauchesne
SIGSEGV
  pc 0x780b3488
  ea 0x40df1200
 r0 00000000   r1 00bf7afc   r2 00000000   r3 00c00400
 r4 00002278   r5 00006604   r6 00004e75   r7 ffffffe8
 r8 00000000   r9 00000028  r10 0000006c  r11 00808cb2
r12 ffffffff  r13 00000000  r14 000061c8  r15 00800400
r16 000c7868  r17 000013ff  r18 000c6b88  r19 40814c1e
r20 00bf7b0e  r21 00c00190  r22 00c00400  r23 00000000
r24 00001401  r25 00000020  r26 00000000  r27 ffff876e
r28 00000000  r29 40df1200  r30 40c60000  r31 68fff000
 f0 0.00000   f1 0.00000   f2 0.00000   f3 0.00000
 f4 0.00000   f5 0.00000   f6 0.00000   f7 0.00000
 f8 0.00000   f9 0.00000  f10 0.00000  f11 0.00000
f12 0.00000  f13 0.00000  f14 0.00000  f15 0.00000
f16 0.00000  f17 0.00000  f18 0.00000  f19 0.00000
f20 0.00000  f21 0.00000  f22 0.00000  f23 0.00000
f24 0.00000  f25 0.00000  f26 0.00000  f27 0.00000
f28 0.00000  f29 0.00000  f30 0.00000  f31 0.00000
 lr 40df1200  ctr 00000000   cr 40101c22  xer 00000000
 pc 40df1200 fpscr 00000000
  0x40df11e0:  Segmentation fault

**Comment by cat7** [comment]
Perhaps this can help:
https://www.emaculation.com/doku.php/sheepshaver_basiliskii_linux

**Comment by stamasd** [comment]
I know how to configure SheepShaver. I've used it for many years, and yes I remember about the memory error, that's why I ran it as root. But this build segfaults.

**Comment by kanjitalk755** [comment]
It was not reproduced in the following environment.

 Host: Debian 11.4 (x86_64)
Guest: MacOS 9.0.4, New World ROM

It may be possible to fix the issue if the reproduction conditions are clarified.

**Comment by kanjitalk755** [comment]
It was not reproduced in the following environment.

Host: Debian 11.4 (x86_64)
Guest: Mac OS J1-8.1, centris650.rom

It may be possible to fix the issue if the reproduction conditions are clarified.

**Comment by stamasd** [comment]
1. Install Funtoo Linux, version 1.4 (current, stable) and update it to the latest version of the portage tree with 'ego sync && emerge -avuDN @world'
2. git clone https://github.com/kanjitalk755/macemu.git
3. cd cd macemu/SheepShaver/src/Unix
4. ./autogen.sh && make
5. start SheepShaver as root with sudo, configure it in the GUI with New World ROM and a HDD image with any of the following (previously installed and working using a previous version of SheepShaver which did not crash): MacOS 8.1, or 8.6. or 9.0.4
6. segfault

**Comment by robxnano** [comment]
Could not reproduce here. Tested on a VM and everything works fine.
![Screenshot at 2022-09-18 21-36-18](https://user-images.githubusercontent.com/89391914/190927722-9357e84c-b1f6-4cdb-a94f-6e7551a6d10c.png)
If you are still having problems, please post your system specs and the contents of your config.log (removing personal information as necessary).

**Comment by buserror** [comment]
I have the same problem here, I narrowed it down to mmap(NULL.... to get the zero page, this fails so it's perhaps something systemd or something else does to 'protect you' by messing stuff up, it's likely we need an extra ACL flag on the exec to allow this to work. Having a look...

**Comment by kanjitalk755** [comment]
See following:

https://www.emaculation.com/forum/viewtopic.php?p=63484
