### ISSUE TITLE
Tap networking windows

### ISSUE THREAD

**Issue by cat7** [kanjitalk755/macemu#149]
With the more recent versions of the openvpn tap driver installed B2/SS will no longer list tap devices when selecting an ethernet interface in the GUI.  I guess this has to do with the switch away from the old ndis5 driver in favour of the ndis6 driver. Installing the old version of the tap driver does not seem to be an option as it will be depricated at some time.
I attempted to set tap and etherguid prefs manually but that failed.

Is this something you could look into?

**Comment by kanjitalk755** [comment]
It's difficult for me to fix this issue.
Welcome a pull request from people familiar with Windows networking.

**Comment by cat7** [comment]
It looks like the issue is actually limited to finding the tap devices, their names, and corresponding guids in the registry. After manually finding the correct guid tap networking still works.

**Comment by cat7** [comment]
Confirmed, fixed. Thanks!
