### ISSUE TITLE
BasiliskII under macOS: System 7 and 7.1 Sound control panel don't make sounds

### ISSUE THREAD

**Issue by emendelson** [kanjitalk755/macemu#151]
With the latest code of BasiliskII running in macOS Monterey on an M1 Mac: the System 7 versions of the Sound control panels do not make any sounds. If I install QuickTime 2.5, it replaces the Sound control panel, and the new control panel works correctly. But the original System 7 versions  of the control panel do not.

**Comment by kanjitalk755** [comment]
When I select `Alert Sounds` in the Sound control panel, the menu bar flashes (visual bell).
I think that the sound will be output if I stop the visual bell, but I don't know how to operate it.

**Comment by RonaldPR** [comment]
Isn't it the other way around? In all System/MacOS versions, also on real hardware, when sound is disabled or not available, the menu bar will flash instead of playing an alert sound.
It seems sound output is different in earlier System 7 versions, maybe related also to different/earlier hardware. If QuickTime 2.5 is installed in System 7, and with it a newer Sound control panel, the sound output device can be selected and sound will work fine.

**Comment by emendelson** [comment]
One other strange thing. Running under macOS, using the QuickTime 2.5 version of the Sound control panel, if I select Volumes, I can not use the "Mute" checkbox. If I click in it, an "X" appears briefly, and then disappears. 

This does not happen in SheepShaver.

**Comment by kanjitalk755** [comment]
>  In all System/MacOS versions, also on real hardware, when sound is disabled or not available, the menu bar will flash instead of playing an alert sound.

I don't know how System 7 determines that the sound device is unavailable when it boots, so I can't work around that.

@emendelson
Please create a separate Issue for different bug.

**Comment by emendelson** [comment]
@kanjitalk755 - I've created a separate issue about the Mute checkbox.

**Comment by emendelson** [comment]
With the new build, this problem still exists. The menubar flashes, but no sound is produced by the original System 7.0.x and 7.1 Sound control panel.

**Comment by kanjitalk755** [comment]
It turned out to be a specification of BasiliskII.
It is a mechanism to call AudioDispatch() by patching the Audio Component in rsrc_patch.cpp,
but System less than 7.5 is not supported.

**Comment by emendelson** [comment]
Yes, I see. It starts around line 285 in rsrc_patch.cpp and says "7.5, 7.6, 7.6.1, 8.0". Maybe no one figured out what to do about earlier versions?

**Comment by RonaldPR** [comment]
Maybe System 7 is different, but what would happen if that was extended with 7.0 and 7.1?
