### ISSUE TITLE
BasiliskII: Sound applet: mute checkbox doesn't work

### ISSUE THREAD

**Issue by emendelson** [kanjitalk755/macemu#152]
Running BasiliskII under both macOS and Windows, using the QuickTime 2.5 version of the Sound control panel, if I select Volumes, I cannot use the "Mute" checkbox. If I click in it, an "X" appears briefly, and then disappears.

In SheepShaver, the Mute button works correctly.

**Comment by kanjitalk755** [comment]
Fixed.
I confirmed under MacOS 7.5.3 and 8.1.
Could you confirm under System 7 with QT?

**Comment by emendelson** [comment]
Yes, this is fixed under System 7 with QT. Thank you. Closed!
