### ISSUE TITLE
Script Editor 1.4.3 crashes SheepShaver on ARM Mac

### ISSUE THREAD

**Issue by emendelson** [kanjitalk755/macemu#154]
Running on an ARM Mac, using Mac OS 9.0.4, Script Editor 1.4.3 causes SheepShaver to crash. The crash does not happen if SheepShaver is set to run under Rosetta, and older versions of Script Editor don't crash when running under ARM.

**Comment by kanjitalk755** [comment]
I tried to fix this issue.
Please test the branch below.

https://github.com/kanjitalk755/macemu/tree/test_lmw_stmw

**Comment by emendelson** [comment]
Yes. This now works correctly. I am very impressed that you were able to solve this!

**Comment by kanjitalk755** [comment]
Merged to the master.
