### ISSUE TITLE
.bin + .cue ?

### ISSUE THREAD

**Issue by Lopez73** [kanjitalk755/macemu#155]
great work!

but i have a question, problem:
I use SheepShaver for Windows (03-12-2022)
https://www.emaculation.com/forum/viewtopic.php?t=5325

and I would like to use Mixed CD (data+audio tracks) for Mac OS 9. Therefore my question:
- is it possible to load these image files and especially to hear the audio tracks from them?
- is it possible to listen to pure audio CDs in Sheepshaver/Mac OS 9?
- I had already addressed the problem in the forum (I would like to play the game Colonization WITH the music)
More information here in the forum: 
https://www.emaculation.com/forum/viewtopic.php?t=11699&sid=3429667ee15c375ac08bd3a4ce0c04f5
Starts at:
by Lopez72 » Fri Jan 27, 2023 6:16 pm

Thank you!

**Comment by RonaldPR** [comment]
The discussion in the forum about this issue starts with this post by Lopez72:
https://www.emaculation.com/forum/viewtopic.php?p=75625#p75625

With latest SheepShaver builds, bin/cue support works in macOS but seems to not work in Windows.

**Comment by kanjitalk755** [comment]
BIN/CUE is not supported in standard builds.
(It is enabled for Xcode projects.)

To enable it:
```
./configure --with-bincue
```

**Comment by cat7** [comment]
Hi, the windows builds I provide are configured with --with-bincue. However, the cdrom is only partly read when a cue file is added to the prefs.

**Comment by kanjitalk755** [comment]
> However, the cdrom is only partly read when a cue file is added to the prefs.

Do you have an easily verifiable BIN/CUE?

**Comment by RonaldPR** [comment]
The files in this download from Macintosh Garden are discussed in the forum:
https://macintoshgarden.org/sites/macintoshgarden.org/files/games/Colonization_bin-cue.zip

The game works fine in macOS, with music. In Windows the music tracks cannot be played.

**Comment by kanjitalk755** [comment]
I installed Colonization and tried it.
A Build with the `--with-bincue` option played the opening music, a build without it didn't.
Seems to be working correctly.

**Comment by cat7** [comment]
How did you add the cue to the prefs?

**Comment by cat7** [comment]
Ok, problem fixed. It seems the cue file contained data from having been zipped on a Mac. Once that data was removed, the cd was recognised correctly and played OK.

**Comment by Lopez73** [comment]
that sounds really great!
can you describe that in a little more detail?
How can I reproduce this with my windows computer?

**Comment by RonaldPR** [comment]
See the forum. Open the cue file in Notepad and remove additional info caused by the OSX/macOS zip format. The content of the file should then only be:
```
FILE "colonization.bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    INDEX 01 01:39:10
  TRACK 03 AUDIO
    INDEX 01 03:45:62
  TRACK 04 AUDIO
    INDEX 01 05:00:35
  TRACK 05 AUDIO
    INDEX 01 07:26:52
  TRACK 06 AUDIO
    INDEX 01 08:24:24
  TRACK 07 AUDIO
    INDEX 01 09:31:02
  TRACK 08 AUDIO
    INDEX 01 10:19:00
  TRACK 09 AUDIO
    INDEX 01 11:05:73
  TRACK 10 AUDIO
    INDEX 01 12:29:49
  TRACK 11 AUDIO
    INDEX 01 14:06:08
  TRACK 12 AUDIO
    INDEX 01 15:46:59
  TRACK 13 AUDIO
    INDEX 01 16:10:67
  TRACK 14 AUDIO
    INDEX 01 17:37:47
  TRACK 15 AUDIO
    INDEX 01 18:26:67
  TRACK 16 AUDIO
    INDEX 01 19:51:23
  TRACK 17 AUDIO
    INDEX 01 21:42:53
  TRACK 18 AUDIO
    INDEX 01 22:43:57
  TRACK 19 AUDIO
    INDEX 01 24:29:48
  TRACK 20 AUDIO
    INDEX 01 25:01:67
  TRACK 21 AUDIO
    INDEX 01 26:19:44
  TRACK 22 AUDIO
    INDEX 01 27:13:02
  TRACK 23 AUDIO
    INDEX 01 28:20:56
  TRACK 24 AUDIO
    INDEX 01 29:49:10
  TRACK 25 AUDIO
    INDEX 01 31:15:12
  TRACK 26 AUDIO
    INDEX 01 32:30:15
  TRACK 27 AUDIO
    INDEX 01 33:15:28

```

**Comment by cat7** [comment]
Oh, please note I "fixed" the wrong cue file... it was for the civilization game, not colonization game. The colonization cue file works just fine.

**Comment by RonaldPR** [comment]
Problem solved. The .cue file was apparently added as `disk` instead of `cdrom` to the prefs.
