### ISSUE TITLE
Command key not working

### ISSUE THREAD

**Issue by Latchkey1998** [kanjitalk755/macemu#156]
Hello I am running sheepshaver on a raspberry pi 4 with an apple design keyboard and mouse connected through a drakware adb2usb when I try to boot up into Mac OS 7.5 and 8.5 the command key does not work every other key works perfectly just except the command key it is using the X server 1.20.4 and the latest sdl version

**Comment by RonaldPR** [comment]
In Windows and Linux builds, Option and Command keys are reversed by default. When you use an Apple keyboard, edit the sheepshaver prefs file in a text editor and change the line
`swap_opt_cmd true`
to
`swap_opt_cmd false`

**Comment by Latchkey1998** [comment]
Yes is did already do that and the command key still does not work

**Comment by RonaldPR** [comment]
With `swap_opt_cmd true` , did the Option key work as Command key?

**Comment by Latchkey1998** [comment]
Yes it did work but I would like to use the command key

**Comment by RonaldPR** [comment]
And with `swap_opt_cmd true` , does the Command key work as Option key?

**Comment by Latchkey1998** [comment]
No

**Comment by RonaldPR** [comment]
Does the key do anything on the host?

**Comment by Latchkey1998** [comment]
I am running it with no gui but I can run keyboard test and it comes up with a key code so it sees it

**Comment by RonaldPR** [comment]
It is late here, I need to go to sleep. Tomorrow kanjitalk755 will have had a look at the issue. If there is still no solution or explanation, I can suggest some tests with keycode files.

**Comment by Latchkey1998** [comment]
Ok thanks

**Comment by kanjitalk755** [comment]
Insert printf around line 2350 of macemu/SheepShaver/src/SDL/video_sdl2.cpp as follows and build SheepShaver.

```
case SDL_KEYDOWN: {
	if (event.key.repeat)
		break;
	int code = CODE_INVALID;
	if (use_keycodes && event2keycode(event.key, true) != CODE_HOTKEY)
		code = keycode_table[event.key.keysym.scancode & 0xff];
	if (code == CODE_INVALID)
		code = event2keycode(event.key, true);
	printf("code=%d\n", code); // insert this line
	if (code >= 0) {
```

What is the value displayed by pressing Command key?

**Comment by Latchkey1998** [comment]
Sdl does not work when I try it it boots into the gui to configure it but when I press start it crashes and leaves no error codes

**Comment by RonaldPR** [comment]
1. Does the logo key (= Windows key on a Windows keyboard and Command key on a Mac keyboard) have a special function in the host OS that may prevent the use in SheepShaver?

This used to be an issue in Windows. Now this is solved by disabling the key in Windows while SheepShaver is used.

2. Exactly what kind of Mac keyboard do you use? A full keyboard with all modifier keys left and right of the space bar, or are you working on a Mac laptop with limited keyboard? If so, which machine?

**Comment by Latchkey1998** [comment]
No the logo key does not have a special function in the Debian command line and I am using an Apple design keyboard which is full sized I am using with an adapter but I tried out qemu running Mac OS 9.2 and the command key works in there

**Comment by RonaldPR** [comment]
I suppose you do not use a keycodes file. If you tell me whether your keyboard is an ANSI or ISO keyboard, I can give you a custom keycodes file to test. (An ANSI keyboard has a a return key in the shape of a horizontal bar, an ISO keyboard has a return key in the shape of a letter "L" upside down.)

**Comment by Latchkey1998** [comment]
It is an ansi keyboard

**Comment by RonaldPR** [comment]
Here is the custom keycodes file (zipped): 
[keycodes-x11-ansi.zip](https://github.com/kanjitalk755/macemu/files/10716373/keycodes-x11-ansi.zip)

In the GUI/Settings enable "Use Raw Keycodes" and browse to the keycodes-x11-ansi file.
Or in prefs file:
keycodes true
keycodefile path to keycodes-x11-ansi

Try both left and right command keys.

**Comment by Latchkey1998** [comment]
The key codes file does not work

**Comment by RonaldPR** [comment]
This is very strange. In 2021 the keycodes were tested in both SheepShaver and BasiliskII with several Linux users and with several different keyboards.
Do all other keys work as expected with the keycodes file?
And SheepShaver was built with SDL 2.0.14 or later?
If nothing was changed in the source code that could explain this issue, I can only assume that the key press somehow does not produce the expected SDL2 scancodes (227 for the left command key and 231 for the right command key). 
The keys work in QEMU, but I do not know if QEMU translates SDL2 scancodes to Mac keycodes, it may give Mac keycodes directly to the emulated machine.

You refer to your keyboard as "an Apple design keyboard", that is a keyboard produced by Apple for Mac?

**Comment by Latchkey1998** [comment]
Some of the keys work most of the letter keys work it's just the special keys like the space bar the delete key etc and yes this keyboard was made for Mac in 1995 it runs on the adb bus along with the adb mouse I am using

**Comment by Latchkey1998** [comment]
If you can't get sheepshaver to work that's fine I am working on qemu now trying to get  either os 10.0 or 10.1 to run since sheepshaver is unstable for me 
And qemu is more stable

**Comment by RonaldPR** [comment]
I doubt that these emulators were tested with vintage adb Apple keyboards in recent years, certainly not the SDL2 versions by kanjitalk755.
