### ISSUE TITLE
SheepShaver for Windows: Fullscreen does not keep aspect ratio

### ISSUE THREAD

**Issue by RonaldPR** [kanjitalk755/macemu#157]
Fullscreen does not keep aspect ratio in SheepShaver for Windows. Used to work correctly in (much?) older builds and does work correctly in current SheepShaver for macOS with compensating black bars at the sides.

See this forum thread: https://www.emaculation.com/forum/viewtopic.php?p=75852#p75852

**Comment by kanjitalk755** [comment]
Didn't reproduce. i.e. the aspect ratio was maintained when switching to fullscreen.

**Comment by kanjitalk755** [comment]
Perhaps it happened when you tried to change to a resolution that the host doesn't support.
Since the host is no longer requested to change resolutions, this phenomenon should not occur.
Please reopen if it happens.
