### ISSUE TITLE
Basilisk on macOS 12.x

### ISSUE THREAD

**Issue by sparky-raccoon** [kanjitalk755/macemu#162]
Hello, 

I followed the steps described in the README.md, but am facing an issue when I attempt a build. 
```
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/sparkyraccoon/Projects/macemu/BasiliskII/src/MacOSX/build/BasiliskII.build/Release/BasiliskII.build/Objects-normal/arm64/Binary/BasiliskII normal arm64 (in target 'BasiliskII' from project 'BasiliskII')
```
Also getting a lot of those warnings : 
```
ld: warning: object file (/usr/local/lib/libgmp.a(randmui.o)) was built for newer macOS version (12.0) than being linked (11.0)
```

Not sure what I need to do. I'm using macOs with Intel and have updated recently (v12.6.4). 
Many thanks !

**Comment by kanjitalk755** [comment]
Have you configured as per this part of README.md?

> On an Intel Mac, change the configure command for both GMP and MPFR as follows, and ignore the make check command:

**Comment by sparky-raccoon** [comment]
I did, configuration seem to succeed for both gmp and mpfr. In config.log :
- gmp : build='skylake-apple-darwin21.6.0'
- mpfr : build='x86_64-apple-darwin21.6.0'

**Comment by kanjitalk755** [comment]
The focus is on `host=` rather than `build=`.
`host=aarch64-apple-darwin` is correct.

**Comment by sparky-raccoon** [comment]
You're right. Still, getting `host=aarch64-apple-darwin` for both GMP and MPFR, the issue might be somewhere else.

**Comment by kanjitalk755** [comment]
I tried it on Catalina, and was able to build successfully with the instructions in the README.md.
(The only difference is that the version of MPFR has been upgraded.)
It may have something to do with the OS version.
But unfortunately my Intel machine cannot be updated to a newer OS than that.

**Comment by kanjitalk755** [comment]
If you don't need BasiliskII to be Universal, you can also build it the same way as the Linux version.

**Comment by RonaldPR** [comment]
Or you can download a ready-built BasiliskII for macOS from this post on Emaculation forum:
https://www.emaculation.com/forum/viewtopic.php?t=7361
Make sure to read also all information below the download links in that post!

**Comment by sparky-raccoon** [comment]
> I tried it on Catalina, and was able to build successfully with the instructions in the README.md. (The only difference is that the version of MPFR has been upgraded.) It may have something to do with the OS version. But unfortunately my Intel machine cannot be updated to a newer OS than that.

Thanks @kanjitalk755 for trying.

> If you don't need BasiliskII to be Universal, you can also build it the same way as the Linux version.

I attempted a build following Linux steps, and got the following results. 
```
/usr/bin/true BasiliskII

./BasiliskII
Basilisk II V1.1 by Christian Bauer et al.
Using prefs file at /Users/sparkyraccoon/.basilisk_ii_prefs
ERROR: Cannot open ROM file
```

> Or you can download a ready-built BasiliskII for macOS from this post on Emaculation forum: https://www.emaculation.com/forum/viewtopic.php?t=7361 Make sure to read also all information below the download links in that post!

Thanks @RonaldPR for the suggestion, I actually started to get Basilisk like this in the first place ... and it doesn't seem to open. There's no popup, nothing happens.

I feel kind of doomed right now. I honestly just want to play Kid Pix 2 once again in my life. 🥵

**Comment by kanjitalk755** [comment]
> That might be good, isn't it ?
If so, I need to figure out the next steps.

The build is successful.
For usage issues, the following user forums are suitable.

https://www.emaculation.com/forum/
