### ISSUE TITLE
Problems with building under Ventura on M1/M2 Mac

### ISSUE THREAD

**Issue by emendelson** [kanjitalk755/macemu#163]
A few problems building under latest version of Ventura and Xcode on an Apple Silicon Mac:

1. There is nothing you can do about this one: Both `gmp` and `mpfr` produce multiple failures (segementation faults) on `make check`. I don't know if this has any effect on the actual builds of BII and SS.

2. BII build fails with a message about minimum versions. The fix is to open the project in Xcode, and replace one instance of 10.11 with 10.13.3 and two instances of 10.7  with 10.13.3.

3. SS fails with a similar message. The fix is to open the project in Xcode and replace three instances of 10.7 with 10.13.3. 

Probably 10.13.0 would work also, but I didn't try it.

**Comment by RonaldPR** [comment]
For my more recent SheepShaver and BasiliskII builds, also before Ventura, I always changed the value 10.7 for "Minimum Deployments" to the earliest macOS version presented as alternative choice in the menu in Xcode, and in Info I then changed "Minimum system version" accordingly (in BasiliskII I added that in Info). For my latest builds that is 10.13 and 10.13.0 respectively.

(I do not see "10.11" anywhere.)

**Comment by emendelson** [comment]
Latest code, just downloaded. Open Basiliskii.xcodeproj in Xcode. Search for 10.11.

<img width="412" alt="Screenshot 2023-04-03 at 11 56 47 AM" src="https://user-images.githubusercontent.com/5208505/229563794-57b7fc08-a3ed-43a2-ba06-b0d893aa48c3.png">

Click on "10.11"; in the editing window, scroll down to Deployment Target, then macOS Deployment Target.

**Comment by RonaldPR** [comment]
Well, without "Find", I would never have encountered it. I never make any changes in Build settings, leave Architectures alone. I just set MinimumDeployments to 10.13 in the General tab, which automatically also changes macOS Deployment Target to macOS 10.13 in Build settings > Deployment.

**Comment by emendelson** [comment]
Your method is much easier. I'll use it in the future. Thank you!

**Comment by kanjitalk755** [comment]
> 1. There is nothing you can do about this one: Both `gmp` and `mpfr` produce multiple failures (segementation faults) on `make check`. I don't know if this has any effect on the actual builds of BII and SS.

See below for a bug report.

https://gmplib.org
https://www.mpfr.org

> 2. BII build fails with a message about minimum versions. The fix is to open the project in Xcode, and replace one instance of 10.11 with 10.13.3 and two instances of 10.7  with 10.13.3.
> 3. SS fails with a similar message. The fix is to open the project in Xcode and replace three instances of 10.7 with 10.13.3.

This is a difficult issue to deal with.
For example, people using El Capitan on older machines won't be able to build and run.

**Comment by emendelson** [comment]
I've filled a bug report for GMP. It's possible that the problems with MPFR may be an effect of the problems in GMP, so I'll file a bug report for MPFR after the GMP issue gets fixed.

I don't how to deal with this problem. Maybe create two project files for each app, one with "Xcode14" in its name?

**Comment by kanjitalk755** [comment]
> I don't know if that's the correct command, but the errors then disappeared from GMP.
> MPFR then built successfully.

Great!

Changed Deployment Target to 10.13 and added a description of it to README.md.
