### ISSUE TITLE
MacOS Ventura 13.5 and MacOS Big Sur 11.7.9 - BasiliskII, BasiliskIIGUI and SheepShaver won't open

### ISSUE THREAD

**Issue by snakebyte69** [kanjitalk755/macemu#166]
Both applications try to open and then close

**Comment by RonaldPR** [comment]
Both SheepShaver and BasiliskII run fine in macOS 13.5 (Ventura)
These emulators will not run by themselves.
You do not write if and how you set up these emulators or possibly if and how you migrated from another machine.

See setup guides for SheepShaver and BasiliskII here:
https://www.emaculation.com/doku.php/sheepshaver_mac_os_x_setup
https://www.emaculation.com/doku.php/basiliskii_osx_setup

Best post support questions in Emaculation forum: https://www.emaculation.com/forum/

**Comment by snakebyte69** [comment]
I read the setup guides and downloaded multiple versions of the Applications
Attempted to build the MacOSX version with XCode and the Unix Version is make
The applications attempt to launch and then close in all cases

**Comment by RonaldPR** [comment]
Better use the ready-built applications that are available on Emaculation forum. They are built from te latest source here.
Then follow the setup guides on Emaculation wiki.

Both SheepShaver and BasiliskII will not run without initial setup.
The Basilisk II Prefs app should run fine.

Also note that modern macOS does not allow apps to be launched from the location where they were downloaded and/or the downloaded archive was expanded. See my reply to your post on Emaculation forum.

**Comment by snakebyte69** [comment]
I have already tried that
The Basilisk II GUI App does not run, opens then closes, no startup screen

**Comment by snakebyte69** [comment]
I can get GMP and MPFR to build using the MacOS X Intel method.
The main build fails, I get the following error.

ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/snake/Downloads/macemu-master/BasiliskII/src/MacOSX/build/BasiliskII.build/Release/BasiliskII.build/Objects-normal/arm64/Binary/BasiliskII normal arm64 (in target 'BasiliskII' from project 'BasiliskII')
(1 failure)

**Comment by snakebyte69** [comment]
I have the exact same issue with MacOS Big Sur 11.7.9 on another Mac

**Comment by kanjitalk755** [comment]
> I can get GMP and MPFR to build using the MacOS X Intel method.

If you're using macOS Ventura, your machine isn't Intel, so ignore Intel method.

**Comment by snakebyte69** [comment]
It's an Intel Mac running Ventura 
<img width="281" alt="Screenshot 2023-08-01 at 11 08 50 pm" src="https://github.com/kanjitalk755/macemu/assets/39090848/ba86827f-6f1f-404f-ab74-7c299a7edf6f">

**Comment by kanjitalk755** [comment]
> macOS Ventiura can still be used on some Intel Macs.

Sorry my mistake.

I just checked if it can be built according to the `README` on an Intel machine (macOS Catalina), and it was successful.
Ventura may require some additional configuration, but I can't confirm.

**Comment by snakebyte69** [comment]
5. A compatible ROM file. Basilisk II will not run without a compatible ROM file. If BasiliskII does not find a compatible ROM file, it will immediately quit on launch.

Sheepshaver - MAC OS ROM
What do you rename the ROM to for BasiliskII?

**Comment by RonaldPR** [comment]
The name is irrelevant for setup with the Basilisk II GUI application. There you can choose the used rom file
The performa.rom usually gives best results.
See setup guide: https://www.emaculation.com/doku.php/basiliskii_osx_setup

**Comment by snakebyte69** [comment]
Solved it.
Edited .basilisk_ii_prefs
added this line

rom /Applications/BasiliskII/MAC.ROM

Used a Performa.rom renamed it to MAC.ROM

It was closing because it couldn't find a ROM and then couldn't open the ROM

**Comment by snakebyte69** [comment]
If you right click on the App and select
"Show Package Contents"
Then select
- Contents
 - MacOS
You will find the BasiliskII app

If you open this you can see any error messages and diagnose the issue

**Comment by snakebyte69** [comment]
BasiliskGUI won't run under Intel Ventura 13.5

BasiliskGUI-bin gives the following error message
"bad CPU type in executable: /Applications/BasiliskII/BasiliskIIGUI.app/Contents/MacOS/BasiliskIIGUI-bin"

**Comment by snakebyte69** [comment]
For example all of these work except one
512KB ROMS
1992-03 - 35C28F5F - Mac LC II.ROM
1989-09 - 368CADFE - Mac IIci.ROM
1990-03 - 4147DD77 - Mac IIfx.ROM
1990-10 - 36B7FB6C - Mac IIsi.ROM
1990-10 - 350EACF0 - Mac LC.ROM
1990-10 - A49F9914 - Mac Classic.rom - does not work
1991-10 - 3193670E - Classic II.ROM

**Comment by snakebyte69** [comment]
All these work
1MB ROMs
1992-03 - 3DC27823 - Quadra 950.ROM
1991-10 - 420DBFF3 - Quadra 700&900 & PB140&170.ROM
1992-10 - 4957EB49 - Mac IIvx & IIvi or Performa 600.ROM
1992-10 - E33B2724 - Powerbook 160 & 165 & 165c & 180 & 180c.ROM
1992-10 - ECFA989B - Powerbook 210 & 230 & 250.ROM
1993-02 - EC904829 - Mac LC III (older).ROM
1993-02 - ECBBC41C - Mac LC III.ROM
1993-02 - ECD99DC0 - Color Classic.ROM
1993-02 - F1A6F343 - Quadra, Centris 610,650.ROM
1993-02 - F1ACAD13 - Quadra, Centris 610,650,800.ROM
1993-10 - 0024D346 - Powerbook Duo 270C.ROM
1993-10 - EDE66CBD - Color Classic II & LC 550 & Performa 275,550,560 & Macintosh TV.ROM
1993-10 - FF7439EE - LC475,575,Quadra 605,Performa 475,476,575,577,578.ROM
1994-04 - 015621D7 - Powerbook Duo 280 & 280c.ROM
1994-07 - 06684214 - LC,Quadra,Performa 630.ROM
1994-07 - FDA22562 - Powerbook 150.ROM
1995-04 - 064DC91D - LC, Performa 580 & Performa 588.ROM

**Comment by snakebyte69** [comment]
SheepShaver Working ROMs
4MB ROMs
1994-03 - 9FEB69B3 - Power Mac 6100 & 7100 & 8100.ROM - NO
1994-04 - 9C7C98F7 - Workgroup Server 9150 80MHz.ROM - NO
1995-01 - 9B7A3AAD - Power Mac 7100 (newer).ROM - NO
1995-04 - 9B037F6F - Workgroup Server 9150 120MHz.ROM - NO
1995-04 - 63ABFD3F - Power Mac & Performa 5200,5300,6200,6300.ROM - NO
1995-08 - 83C54F75 - Powerbook 2300 & PB5x0 PPC Upgrade.ROM - NO
1995-08 - 96CD923D - Power Mac 7200&7500&8500&9500 v1.ROM - YES
1995-08 - 9630C68B - Power Mac 7200&7500&8500&9500 v2.ROM - YES
1996-08 - 6F5724C0 - PowerMac, Performa 6400.ROM - YES
1996-10 - 83A21950 - PowerBook 1400, 1400cs.ROM - NO
1997-02 - 6E92FE08 - Power Mac 6500.ROM - YES
1997-02 - 960E4BE9 - Power Mac 7300 & 7600 & 8600 & 9600 (v1).ROM - YES
1997-02 - 960FC647 - Power Mac 8600 & 9600 (v2).ROM - YES
1997-11 - 78F57389 - Power Mac G3 (v3).ROM - YES
1997-11 - 79D68D63 - Power Mac G3 desktop.ROM - YES
1998-03 - CBB01212 - PowerBook G3 Wallstreet.ROM - NO
1998-08 - B46FFB63 - PowerBook G3 Wallstreet PDQ.ROM - NO

**Comment by snakebyte69** [comment]
SheepShaver Working ROMs

Other

4400.ROM - YES
5500.ROM - YES

**Comment by RonaldPR** [comment]
> BasiliskGUI won't run under Intel Ventura 13.5
> 
> BasiliskGUI-bin gives the following error message "bad CPU type in executable: /Applications/BasiliskII/BasiliskIIGUI.app/Contents/MacOS/BasiliskIIGUI-bin"

You got the wrong GUI app. BasiliskIIGUI.app is a 32-bit only app.
On Ventura you need the Basilisk II GUI.app.

**Comment by snakebyte69** [comment]
Link?
I can't find it in the Forum, how about putting the latest releases in this Github?

**Comment by emendelson** [comment]
It's a different project by a different author. There's a link to it in the first post in the first thread in the BasiliskII forum, but this will save you the trouble of looking for it:

https://www.emaculation.com/forum/viewtopic.php?f=6&t=10454

**Comment by snakebyte69** [comment]
BasiliskII GUI is now working

Thanks for all your help!
