### ISSUE TITLE
Basilisk and SheepShaver Windows GUIs behaviour change request

### ISSUE THREAD

**Issue by cat7** [kanjitalk755/macemu#170]
When the "Close" buttons of the Windows GUIs are clicked SheepShaver.exe or BasiliskII.exe are started. This is confusing and contrary to normal window behaviour. Normally I would expect that the GUI closes without saving the prefs, and without starting the application.

If possible could a "Save" button be added to save the prefs but not starting the applications? And the "Close" button be reserved for closing the window without saving the prefs and starting the applications? 

A second best solution would be that the "Close" button saves the prefs and closes the GUI but does not start the application.

Thanks for looking into this.

**Comment by RonaldPR** [comment]
Similar to the macOS Basilisk II GUI application? Buttons there do what the user would expect.
The Save button just saves the settings
The Start button saves the settings and opens the emulator
The Quit button quits the application without saving
The Close button does what the Quit button does

![basosx_setup_3disks_2](https://github.com/kanjitalk755/macemu/assets/1886290/73814f6c-a5ec-4fc0-a5b9-4336bab6e0a3)

**Comment by cat7** [comment]
If possible, yes.
