### ISSUE TITLE
Garbled colors in 256 color programs

### ISSUE THREAD

**Issue by dpwalters** [kanjitalk755/macemu#171]
The system is 64bit x86_64 linux with SDL2 video. The millions of color programs work fine, however a program that requires
256 colors and it garbles the output for some reason. I don't really have a lot of time to investigate why. I did try the "software" SDL
renderer.

**Comment by kanjitalk755** [comment]
Didn't reproduce.

Debian 12.1 x86_64
SDL2 2.26.5
sdlrenderer software

**Comment by dpwalters** [comment]
I was able to solve the problem by using a newer libsdl2, (2.0.4). (If I find the time I may go and find out why it didn't work
correctly with the older libsdl2)

**Comment by kanjitalk755** [comment]
As described in the `README`, install SDL2 version 2.0.14 or higher.
Otherwise, it may not work as expected.
