### ISSUE TITLE
Ubuntu 22.04 VHD support

### ISSUE THREAD

**Issue by rvanlaar** [kanjitalk755/macemu#172]
The easy ability to make snapshots brought me to experiment with it.
Unfortunately I'm unable to build macemu with vhd.

I installed libvhdi-dev and libvdhi-utils, but thtat didn't help.
As per issue #124: config.log had these lines `/usr/bin/ld: cannot find -lvhd: No such file or directory`

What's do I need to install to enable vhd support?

Note: This issue looks a lot like: https://github.com/kanjitalk755/macemu/issues/124

**Comment by kanjitalk755** [comment]
VHD related hasn't changed in over a decade.
Probably, it seems that it does not work in the current environment without updating.

**Comment by rvanlaar** [comment]
It seems that it's not easy to get a build with VHD.
Especially since there's no available documentation on how to build it.

After some digging I found the following:

VHD support was introduced in this commit. 
https://github.com/kanjitalk755/macemu/commit/7665252790c18158a37d80a0759cc6faf050b15b

Luckily the commit mentions the dependencies:
```
    The support uses the open source libvhd library which is part of xen,
    available here:
      http://www.xen.org/products/xen_source.html
    
    The piece that's needed is libvhd which is in tools/blktap2 and it can
    be separately compiled.
    The vhd-util enables creation of vhd disks and snapshots.
 ```

Unfortunately blktap2 has been deprecated in 2019.
http://xenbits.xen.org/gitweb/?p=xen.git;a=commit;h=5c883cf036cf5ab8b1b79390549e2475f7a568dd
