### ISSUE TITLE
[Help] Eject CD rom using keybind?

### ISSUE THREAD

**Issue by Grieverheart** [kanjitalk755/macemu#175]
I'm trying to install a game that uses 2 CD roms and when the installer asks for CD2 I drag and drop it to Basilisk II and it continues, but at some point it asks CD1 again. Unfortunately, the current implementation does not allow CD swapping. Since the installer is fullscreen, there is no way for me to eject the CD-ROM through the GUI. Is there a keybind for ejecting the CD-ROM? If not, is it possible to change the dragndrop behavior so that it replaces the CD image when one is already mounted?

**Comment by kanjitalk755** [comment]
There is no keybind to eject.
Also, a mounted image cannot be replaced.

Even if you force eject or replace on the host side, there is no way to notify the guest side and it will not function properly.

**Comment by Grieverheart** [comment]
@kanjitalk755 I modified `CDRINDrop` like this:
```C++
void CDROMDrop(const char *path) {
	if (!drives.empty()) {
		cdrom_drive_info &info = drives.back();
		if (!info.drop) {
			info.fh = Sys_open(path, true, true);
			if (info.fh)
				info.drop = true;
		}
        else
        {
            SysAllowRemoval(info.fh);
            SysEject(info.fh);
            WriteMacInt8(info.status + dsDiskInPlace, 0);
            info.twok_offset = -1;
            info.close_fh();
            info.fh = NULL;
            info.drop = false;
			info.fh = Sys_open(path, true, true);
			if (info.fh)
				info.drop = true;
        }
	}
}
```
This worked for my installation, but indeed, the desktop does not get updated. How does the CD-ROM driver normally work when the eject button is pushed? The OS must somehow get notified of that. Isn't it possible to mimic this functionality?

**Comment by cat7** [comment]
Perhaps this app (with source code) helps? https://macintoshgarden.org/apps/eject-version-101

**Comment by kanjitalk755** [comment]
When I executed that, the emulator's eject process was called, but the guest Finder did not detect that it had been ejected.

**Comment by emendelson** [comment]
None of those eject utilities on Macintosh Garden seem to work on BII or SS.
