### ISSUE TITLE
MMU emulation

### ISSUE THREAD

**Issue by lg0735** [kanjitalk755/macemu#176]
Currently no 68K/PPC mac emulator (other than QEMU, but it's kinda slow) supports actually emulating the MMU, which would make the emulation more accurate, and would slow the emulation down to closer to the real speed of an actual 68K/PPC mac. 

Now obviously I understand this is a big task, so this issue should probably be used as a progress issue.

**Comment by kanjitalk755** [comment]
There is no plan to implement MMU in this fork.
