### ISSUE TITLE
Apeiron ADB Mouse Issue

### ISSUE THREAD

**Issue by reedlove** [kanjitalk755/macemu#180]
When trying to play "Apeiron" on a fresh install of Mac OS 7.5.5, the game quits and the following message pops up: "**Couldn't find a mouse device attached to the ADB chain. You are likely using a mouse substitute that is currently not supported by Apeiron.**"
![Screenshot from 2023-10-29 22-42-28](https://github.com/kanjitalk755/macemu/assets/11276590/90a50ed4-21c7-4707-902a-a95525f2d7b9)

**Comment by reedlove** [comment]
Apeiron excuted the invalid command? It's a bummer because I remember playing it on my Dad's IIci and in older versions of Basilisk II with no issues. I thought there was some sort of "enhanced adb" support at one point or another. I was hoping to stick to m68k on Basilisk II. XP

**Comment by kanjitalk755** [comment]
If you can identify the source from which a working Basilisk II was built, this issue may be fixed.

**Comment by reedlove** [comment]
So from what I have found, it appears that this feature was added to the old Windows NT builds created by "Lauri Pesonen". I've only done a little bit of digging, but someone mirrored the source code from one of the post builds that has the "Normal ADB mouse emulation".

[](https://github.com/rakslice/BasiliskII_win32/tree/master/src
)
The enhancement is listed under the Windows-specific documentation.

Hopefully that helps. Apparently it fixes Marathon as well? Haven't tested it.

**Comment by kanjitalk755** [comment]
I tried Visual C++ 6 according to `Tech.win32.txt`, but unfortunately could not open the workspace.

**Comment by kanjitalk755** [comment]
It seems to work correctly with SheepShaver.

**Comment by kanjitalk755** [comment]
I have managed to build and run BasiliskII-build142.

https://github.com/kanjitalk755/BasiliskII-build142

And found the difference and fixed this issue.

**Comment by reedlove** [comment]
Yay! Thanks for that! =]

**Comment by reedlove** [comment]
So I just built and tested the current source that contains the ADB fix. So Apeiron will successfully start now without complaining about ADB mouse compatibility, but unfortunately the mouse input doesn't seem to register once the game starts.

**Comment by reedlove** [comment]
So I'm able to start Apeiron. Navigate the menus with the mouse and begin a game. Once the game starts, you would normally move the vehicle around using the mouse and fire with the mouse button. Unfortunately, the vehicle just sits there and does not acknowledge the movement of the mouse.

**Comment by reedlove** [comment]
That did it! I totally forgot about the mouse grabbing combo. Maybe include a hint in the title bar?
Works great, and thank you again for keeping Basilisk II alive! =D

**Comment by kanjitalk755** [comment]
The title can be configured by user.
For example, append following line to `BasiliskII_prefs`:

```
title Press control+F5
```

**Comment by reedlove** [comment]
> The title can be configured by user. For example, append following line to `BasiliskII_prefs`:
> 
> ```
> title Press control+F5
> ```

Very true. Thank you again for all of your hard work! =]

**Comment by kanjitalk755** [comment]
You can now start BasiliskII with mouse grabbed.
See #191.
