### ISSUE TITLE
Lucasarts CD Games go very slow

### ISSUE THREAD

**Issue by ualaa1** [kanjitalk755/macemu#181]
I tested Sam and Max and The Dig CD versions on both Sheepshaver and Basilisk II. I have tried increasing the memory of the programs, as well as mount the volume in the program instead of mounting them on a virtual drive, and tried downgrading windows size. While the music and sound seem to go at the correct speed, the graphics seem to go in slow motion.

**Comment by kanjitalk755** [comment]
If BII and SS are Windows versions, the reason is the same as #182.
