### ISSUE TITLE
The Quest (1995) will refuse to re-open after being closed

### ISSUE THREAD

**Issue by ualaa1** [kanjitalk755/macemu#185]
This is an obscure game, can be found at https://macintoshgarden.org/games/the-quest-0
After moving the main program onto the desktop from CD, opening the program, quitting, and then re-opening it, I get this error message:
![bandicam 2023-11-22 22-21-15-485](https://github.com/kanjitalk755/macemu/assets/68984176/4b5f3ca3-22c3-4dd2-9a7f-2638546e93c5)

**Comment by kanjitalk755** [comment]
Doesn't reproduced.
