### ISSUE TITLE
Opening King's Quest V causes desktop to be in Black and White

### ISSUE THREAD

**Issue by ualaa1** [kanjitalk755/macemu#186]
Prior to opening the game, you will need to apply https://macintoshgarden.org/games/sierra-patch to work
Game is also in color and not in black and white, it just turns desktop into black and white

![bandicam 2023-11-23 15-04-09-956](https://github.com/kanjitalk755/macemu/assets/68984176/dff7d1d3-2f6b-4030-96e9-645420a885c6)

**Comment by kanjitalk755** [comment]
The same thing happens when I run it with QEMU.
I think that's the spec for this game.
