### ISSUE TITLE
Redump Split bin and cue files does not seem to be supported

### ISSUE THREAD

**Issue by ualaa1** [kanjitalk755/macemu#187]
Game downloaded from https://archive.org/details/applemacintoshusanew1.redump
How it looks like on the prefs screen:
displaycolordepth 0
disk C:\Users\19099\Desktop\em\Mac alt 2\mac3.hfv
cdrom C:\Users\19099\Desktop\em\Mac alt 2\MACisos\Eastern Mind - The Lost Souls of Tong Nou (USA).cue

Cue file: https://archive.org/download/applemacintoshusanew1.redump/Eastern%20Mind%20-%20The%20Lost%20Souls%20of%20Tong%20Nou%20%28USA%29.zip/Eastern%20Mind%20-%20The%20Lost%20Souls%20of%20Tong%20Nou%20%28USA%29.cue

When I try to open the cd drive, it only shows a file called track one
![bandicam 2023-11-23 15-30-10-610](https://github.com/kanjitalk755/macemu/assets/68984176/8b4e1338-0d06-4325-a947-9e020f6c1885)

**Comment by kanjitalk755** [comment]
BIN and CUE files only support one-to-one correspondence.

**Comment by ualaa1** [comment]
Well, split bin files have worked on playstation emulators and DOS emulators and SEGA cd emulators, from what I have tested, so I think supporting split bin files can be something to look into.
See https://archive.org/download/applemacintoshusanew1.redump
The one I was testing is called [Eastern Mind - The Lost Souls of Tong Nou (USA).zip](https://archive.org/download/applemacintoshusanew1.redump/Eastern%20Mind%20-%20The%20Lost%20Souls%20of%20Tong%20Nou%20%28USA%29.zip)

**Comment by kanjitalk755** [comment]
A pull request is welcome.

**Comment by ualaa1** [comment]
If you would really want to get someone to do a pull request, I would suggest re-opening the issue, as well as  https://github.com/kanjitalk755/macemu/issues/188 and https://github.com/kanjitalk755/macemu/issues/182 so that more people can see it and offer a pull request
