### ISSUE TITLE
Warcraft- Redbook Audio Tracks does not play

### ISSUE THREAD

**Issue by ualaa1** [kanjitalk755/macemu#188]
In Warcraft: Orcs & Humans, unlike the DOS version, the mac version uses redbook audio during in-game. In order to replicate this bug, start a campaign (human or orc). There is only sound effects where redbook audio should be playing. 
I made sure to use bin-cue version and also made sure to mount it as a CDROM and not as a disk drive

**Comment by kanjitalk755** [comment]
In CDROMControl(), neither command 103 (AudioTrackSearch) nor command 104 (AudioPlay) was executed.
It cannot be played on anything other than these.
It is unclear how Warcraft play CD audio on a real machine.

**Comment by ualaa1** [comment]
Warcraft does play in-game redbook audio. I'm pretty sure Blizzard probably has something playing in the background.
https://www.emaculation.com/forum/viewtopic.php?t=10220 see this post
 _Warcraft tries to open the Internal CD drive as a recording device and uses playthrough to simulate output. This is problematic, because it requires extending driver support to the Sound Input Manager. [A skeleton of useful code exists in audio.cpp](https://github.com/spolsley/macemu/blob/cdaudio_test/BasiliskII/src/audio.cpp#L616), but the 68k assembly for icon loading is indecipherable to me. It crashes SheepShaver and fails to build in BasiliskII._

**Comment by kanjitalk755** [comment]
According to the thread above, this issue seems difficult to fix.
