### ISSUE TITLE
Tap on a real trackpad not very well detected in emu

### ISSUE THREAD

**Issue by OulanB** [kanjitalk755/macemu#19]
On my mbp, the tapping on the trackpad is not very well detected on the emu side...

here is a changed adb.cpp using a circular buffer to memorize the mouse button actions
as attachment.

It works quite good on sheepshaver with os9.0.4.

On basilisk and os8.1 selecting an entry in a menu is not very nicely detected. The culprit could be the os8.1 as on os9.0.4 it is ok and every other 'tapping as clicking' is detected

P.S. I need to use an old Xcode 10.1 to have a good binary. With Xcode 11.3 I got some troubles : ie acrobat 4.05 can not open correctly its read-me.pdf on sheepshaver.

Olivier
[adb.cpp.txt](https://github.com/kanjitalk755/macemu/files/3992416/adb.cpp.txt)

**Comment by kanjitalk755** [comment]
Could you create a pull request for this issue?

**Comment by kanjitalk755** [comment]
Merged(#31).
