### ISSUE TITLE
Problem and fix for building BasiliskII on Raspberry pi

### ISSUE THREAD

**Issue by dantchapman** [kanjitalk755/macemu#190]
Firstly - thank you for supporting this! - I've very much enjoyed reliving the days of MacOS 7 and 8
I'm not entirely sure why , but I needed to swap the order of -lgmp -lmpfr in he configure.ac file to successfully link BasiliskII on my pi:

```
diff --git a/BasiliskII/src/Unix/configure.ac b/BasiliskII/src/Unix/configure.ac
index 27bf238c..78ba7316 100755
--- a/BasiliskII/src/Unix/configure.ac
+++ b/BasiliskII/src/Unix/configure.ac
@@ -1826,7 +1826,7 @@ for fpe in $FPE_CORE_TEST_ORDER; do
         FPE_CORE="IEEE fpu core (MPFR)"
         DEFINES="$DEFINES -DFPU_MPFR"
         FPUSRCS="$UAE_PATH/fpu/fpu_mpfr.cpp"
-           LIBS="$LIBS -lgmp -lmpfr"
+           LIBS="$LIBS -lmpfr -lgmp"
          else
         FPE_CORE="IEEE fpu core"
         DEFINES="$DEFINES -DFPU_IEEE"
```
The original works fine on my MacBook... I'm not expert enough to explain why the order matters on the pi

**Comment by dantchapman** [comment]
I think putting lgmp to the left is 'correct' as the linker searches from left to right (https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc). as mpfr is dependent on gmp, it should be -lmpfr -lgmp.. Though I'm certainly no expert

**Comment by kanjitalk755** [comment]
Since either order was fine with Debian on a PC, I adjusted it to Raspberry Pi.
Fixed.
