### ISSUE TITLE
How to launch with mouse grabbed by default?

### ISSUE THREAD

**Issue by dantchapman** [kanjitalk755/macemu#191]
This may be a better question raised elsewhere - please let me know if so.
I'm very pleased to see that mouse support is now working again in BasiliskII for ADB mouse games such as Apieron. This is fantastic! What I'd like to do is launch with mouse_grabbed = true.
I've been able to hack this in my local build by calling grab_mouse() in driver_base::init() (video_sdl2.cpp), but could not immediately find any way to set this in the prefs file (its very possible I'm missing something obvious). Is this something that would be useful to add for others?

**Comment by kanjitalk755** [comment]
Added prefs item `init_grab`.
Append following line to `.basilisk_ii_prefs` or `.sheepshaver_prefs`.

```
init_grab true
```

However, `init_grab` is ignored when `hardcursor` is true in SheepShaver.
