### ISSUE TITLE
Cannot map usable RAM area

### ISSUE THREAD

**Issue by plleg** [kanjitalk755/macemu#199]
Compiled on Raspberry PI 5 8 gig

> sudo ./SheepShaver
SheepShaver V2.5 by Christian Bauer and Mar"c" Hellwig
No prefs file found, creating new one at /root/.config/SheepShaver/prefs
ERROR: Cannot map usable RAM area. Try to decrease the MacOS RAM size.

> cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by kanjitalk755** [comment]
>> No prefs file found, creating new one at /root/.config/SheepShaver/prefs

SheepShaver will not work properly unless you create a preference file that matches your environment.
Refer to the following site.

https://www.emaculation.com/doku.php/sheepshaver
