### ISSUE TITLE
MSYS2 - Basilisk II - -flto=auto build flag - checking floating point format... configure: error: Unknown floating point format

### ISSUE THREAD

**Issue by shoober420** [kanjitalk755/macemu#200]
Following the instructions on https://www.emaculation.com/doku.php/compiling_sheepshaver_basilisk, when running `./configure --with-bincue` for Basilisk II on MSYS2 using Windows 11, I get this error.

`checking floating point format... configure: error: Unknown floating point format`

Full Build Log:
[buildlog.txt](https://github.com/user-attachments/files/16114612/buildlog.txt)

SheepShaver compiles fine. I think I need to install lib32-mpfr, but theres no such package in the official Arch repo or the AUR.

**Comment by kanjitalk755** [comment]
Unfortunately, I don't have an environment to test it on Windows 11.

> I think I need to install lib32-mpfr, but theres no such package in the official Arch repo or the AUR.

MPFR is not required in x86 environment.

**Comment by shoober420** [comment]
I found out what it was. I use optimized build flags, and enable LTO is the reason for the error (-flto=auto). Is there a way that Basilisk II can support LTO by enable the -flto=auto build flag?

**Comment by shoober420** [comment]
I just compiled Basilisk II on my Arch Linux machine with the same build flags and did not encounter the error, so this is strictly in MSYS2 environments.

**Comment by kanjitalk755** [comment]
The word `LTO` reminded me that a similar problem occurred on Linux (#194).
I have also applied it to Windows version, so try with the latest source.

**Comment by shoober420** [comment]
Basilisk II now compiles successfully when -flto=auto is used, thank you.
