### ISSUE TITLE
Happyweed runs too fast

### ISSUE THREAD

**Issue by shoober420** [kanjitalk755/macemu#201]
Im trying to play Happyweed using Basilisk II, and the game runs way too fast. Ive tried to use the "Slo-Mo" program to make the game play at the correct speed, but it makes it run very choppy. I tried lowering the refresh rate to 30hz and 15hz, but the game still will run too fast. Is there anyway to make the game run at the correct speed?

**Comment by kanjitalk755** [comment]
For example, add the following line to `BasiliskII_prefs` (for Windows):

```
delay 1000
```

Adjust the value ​​for appropriate speed.

**Comment by shoober420** [comment]
:Slo-Mo Active:

Thanks homie.

I actually made a YouTube video about it because i couldnt find anything about it.
https://youtu.be/QsN2ALNvH4s?si=mN3ThRoWjdupGBwZ
