### ISSUE TITLE
How to replace the Windows icon in BII/SS for Windows?

### ISSUE THREAD

**Issue by emendelson** [kanjitalk755/macemu#202]
This is not an issue, just a question. In Windows builds, the desktop icon for the Windows host looks very crude and I would like to replace it. I think the icon is in posix_emu.cpp as `my_comp_ico` - but I can't be sure of how to replace it. I *think* I need to open an image in GIMP and export it as C source code, but if anyone has more specific instructions, I would be grateful.

EDIT: The icon does not seem to be in posix_emu.cpp as `my_comp_ico` : when I replaced every hex string in that code with zeroes, the same Windows-computer icon appeared on the desktop of the built executable. So where does that icon come from??

**Comment by kanjitalk755** [comment]
According to `posix_emu.cpp`, the icon can be changed in the following way.
1. Set `my_comp_icon[]` to the contents of custom icon file's resource fork.
1. Build `BasiliskII.exe`.
1. Delete `Virtual\ Desktop/Icon%0D` under the directory where `BasiliskII.exe` is located.
1. Launch `BasiliskII.exe`.

**Comment by emendelson** [comment]
Thank you! I had to remove the entire Virtual Desktop folder, not just the Icon%0D file, but I eventually got a generic icon for the Windows host. This is progress. Thank you again!
