### ISSUE TITLE
Linux port must drop /dev/dsp from OSS, and use either SDL2, PulseAudio, or Pipewire for sound

### ISSUE THREAD

**Issue by malespiaut** [kanjitalk755/macemu#204]
Hello,

I've used SheepShaver on Linux, and everything works fine, except for the sound, which relies on accessing `/dev/dsp` which is part of OSS.

OSS isn't used anymore in the Linux world, and SheepShaver must switch to a modern alternative. That is SDL, or Pulseaudio, or Pipewire.

Great work nonetheless.

**Comment by kanjitalk755** [comment]
I do not actively remove old parts of the source.
The audio is actually output by SDL.
When you run SheepShaver, you should see a message like the one below.

```
Using SDL/pulseaudio audio output
```
