### ISSUE TITLE
Civilization II on B2 systematically crashes on a Linux host, works well on a Windows host

### ISSUE THREAD

**Issue by NovHak-Linux** [kanjitalk755/macemu#206]
I already posted the problem [on the E-Maculation forums](https://www.emaculation.com/forum/viewtopic.php?t=12270), but I’ll explain again here, hoping this fine wall of text won’t rebuke too many !

After some difficulties, I finally managed to run Civilization II on B2, on my Linux laptop (Ubuntu 24.04). Everything was well, until a system update that occurred during between the 22nd and the 23rd of august. After the update, each and every time I launch the program, OS 7.6.1 immediately crashes with a _CHK Error_.

I tried the latest [AppImage](https://github.com/Korkman/macemu-appimage-builder/), the Ubuntu stock `basilisk2` package, and compiled the program myself with various memory options : `direct`, `banks` and `real`, all with the same result, CHK Error upon program execution.

Having serious reasons to suspect a host-specific problem, I switched to Windows and tried [the Windows build](https://www.emaculation.com/forum/viewtopic.php?t=5282)… and it worked perfectly.

In both cases, I tried to emulate the same guest : same ROM (performa 500, modelid 74 i.e. gestalt 80), same RAM (128 MB), same CPU (68030 w/o FPU), same OS (Mac OS 7.6.1 French), same disk size and format (2 GiB HFS… what else than HFS on OS 7.6.1 anyway ?).

It _may_ be worth noticing that I first wanted to install the gold edition of Civ II, which is PPC only, so I tried Sheepshaver w/ OS 8.6, but that didn’t work : the game was starting, but the guest was freezing upon unit movement, which happens _very soon_ in game. I had the same freeze upon unit movement on B2 & FPU enabled with the vanilla edition of the game, and with the CPU set to 68040, OS would crash with the CHK Error mentioned before. That’s how I ended up with a 68030 w/o FPU, which worked fine for some weeks, until that recent system update, making the game effectively unplayable on Linux.

But now, on a Windows host, even the gold edition works well on Sheepshaver.

I tried to blame the Linux update first. The update has indeed been quite large, including a `glibc` update, no kernel update though… but it turns out, or so they say, that the update was a “no-change build” the description being “Fix framepointer flags for s390x and ppc64el”, hence other architectures than my amd64.

My theory is that there’s something wrong with the Linux specifics of B2 and Sheepshaver, that makes it susceptible to subtle changes, such as time management maybe. I’m not picking that out of the blue, since I noticed the similar warning messages when launching B2 and SS on Linux :
- On B2 : `WARNING: RmvTime(000f4b3e): Descriptor not found`
- On SS : `WARNING: RmvTime(00247414): Descriptor not found`

So that’s where I am. Your insights are welcome !

**Comment by kanjitalk755** [comment]
I tried the macOS, Linux, and Windows versions, but only the Linux version froze.

The warning about `RmvTime` appears on all types of hosts, so it's probably not a problem.

Regarding the timer, the difference is that the Windows version does not implement a high-precision timer.
I disable it by commenting out the following lines, but it still froze.

https://github.com/kanjitalk755/macemu/blob/e517d73f0cd2e4fed637717164e1496374618115/BasiliskII/src/Unix/sysdeps.h#L503-L504

I also tried building the macOS version using the same method as for Linux, and it worked fine.
So, the generated Makefile etc. seem to be OK.

At this point, I have no idea what the problem is with the Linux version, and it would be difficult for me to fix it.

**Comment by NovHak-Linux** [comment]
Thanks for your reply, and your involvement in trying to solve the problem !

Despite being reproducible, the problem seems complex. I was pointed to [a thread](https://eab.abime.net/showpost.php?p=1095651&postcount=40) (starts at post 40) with people complaining about being unable to run Civ II, with the same symtoms (CHK error)… but it’s with the Shapeshifter emulator on an Amiga host, so not sure it really helps.

The solutions of the Shapeshifter problem vary and seem very random, some changing the memory requirement (⌘I), some changing the date. I’ve tried all this anyway, with no more luck.

I’ve suspected an AppArmor change, but the last one dates back to 2024-07-16, so that’s not it.

Here’s a list of external libraries & files (including the ELF interpreter) that the [AppImage](https://github.com/Korkman/macemu-appimage-builder) of B2 is depending upon, i.e. outside of the AppImage, hence taken from the host system :
```
linux-vdso.so.1
libutil.so.1
libpthread.so.0
librt.so.1
libX11.so.6
libstdc++.so.6
libm.so.6
libgcc_s.so.1
libc.so.6
libuuid.so.1
libasound.so.2
libdl.so.2
libxcb.so.1
libfontconfig.so.1
/lib64/ld-linux-x86-64.so.2
libfreetype.so.6
libz.so.1
libresolv.so.2
libharfbuzz.so.0
libexpat.so.1
libbz2.so.1.0
libbrotlidec.so.1
libbrotlicommon.so.1
libgpg-error.so.0
```

I’m assuming it’s a change in one of those files.

**Comment by NovHak-Linux** [comment]
[I went to the Apple discussion forum](https://discussions.apple.com/thread/255744800) with little hope, but it turned out better than I expected !

[System_Error.pdf](https://github.com/user-attachments/files/16879847/System_Error.pdf)

**Comment by NovHak-Linux** [comment]
Failing to find the origin of the problem for now. Tried with the original dynamic libraries & ELF interpreter (i.e. before the system update), still the same CHK error.

Now I’m trying to prevent that CHK exception to be raised, no matter the consequences that could arise (possibly some “harder” crash), just to see what happens next.

To that effect, I’m assuming _CHK error_ is in fact a CPU-raised exception, following execution of either the CHK or CHK2 instruction, as [table 8-1](https://www.nxp.com/docs/en/reference-manual/MC68030UM-P2.pdf) suggests.

One can see indeed in `../uae_cpu/gencpu.c` what looks very much like a raise of exception no. 6 under some conditions upon execution of CHK or CHK2.

So I made the following changes to `../uae_cpu/gencpu.c`, commenting out the original and replacing with the line below :
```c
     case i_CHK:
	printf ("\tuaecptr oldpc = m68k_getpc();\n");
	genamode (curi->smode, "srcreg", curi->size, "src", 1, 0);
	genamode (curi->dmode, "dstreg", curi->size, "dst", 1, 0);
//	printf ("\tif ((uae_s32)dst < 0) { SET_NFLG (1); Exception(6,oldpc); goto %s; }\n", endlabelstr);
	printf ("\tif (false) { SET_NFLG (1); Exception(6,oldpc); goto %s; }\n", endlabelstr);
//	printf ("\telse if (dst > src) { SET_NFLG (0); Exception(6,oldpc); goto %s; }\n", endlabelstr);
	printf ("\telse if (false) { SET_NFLG (0); Exception(6,oldpc); goto %s; }\n", endlabelstr);
	need_endlabel = 1;
	break;

     case i_CHK2:
	printf ("\tuaecptr oldpc = m68k_getpc();\n");
	genamode (curi->smode, "srcreg", curi->size, "extra", 1, 0);
	genamode (curi->dmode, "dstreg", curi->size, "dst", 2, 0);
	printf ("\t{uae_s32 upper,lower,reg = regs.regs[(extra >> 12) & 15];\n");
	switch (curi->size) {
	 case sz_byte:
	    printf ("\tlower=(uae_s32)(uae_s8)get_byte(dsta); upper = (uae_s32)(uae_s8)get_byte(dsta+1);\n");
	    printf ("\tif ((extra & 0x8000) == 0) reg = (uae_s32)(uae_s8)reg;\n");
	    break;
	 case sz_word:
	    printf ("\tlower=(uae_s32)(uae_s16)get_word(dsta); upper = (uae_s32)(uae_s16)get_word(dsta+2);\n");
	    printf ("\tif ((extra & 0x8000) == 0) reg = (uae_s32)(uae_s16)reg;\n");
	    break;
	 case sz_long:
	    printf ("\tlower=get_long(dsta); upper = get_long(dsta+4);\n");
	    break;
	 default:
	    abort ();
	}
	printf ("\tSET_ZFLG (upper == reg || lower == reg);\n");
	printf ("\tSET_CFLG_ALWAYS (lower <= upper ? reg < lower || reg > upper : reg > upper || reg < lower);\n");
//	printf ("\tif ((extra & 0x800) && GET_CFLG) { Exception(6,oldpc); goto %s; }\n}\n", endlabelstr);
	printf ("\tif (false) { Exception(6,oldpc); goto %s; }\n}\n", endlabelstr);
	need_endlabel = 1;
	break;
```

Recompiled and tested… but it doesn’t work (like nothing has changed) ! I suppose either I did something wrong, or _CHK error_ is not a CPU-raised exception, or something else in the code raises that exception. The only ones that raises exception 6 explicitly are CHK and CHK2, but I see some other places where the exception number is variable.

Is there any chance I’m on the good track, or am I completely wrong here ?

**Comment by kanjitalk755** [comment]
Eventually CHK error detects, but the problem occurs even earlier.

If you run it on gdb, you will see that SIGSEGV occurs after starting Civ II, and if you continue several times, a CHK error alert appears.

**Comment by NovHak-Linux** [comment]
I hear you, but I suppose the error does come from a thrown exception somewhere in the 68030 emulation, especially considering Mac OS mentions “CHK error”, not “addressing error”, “error 2” or something like that. And I’m curious about disabling the exception and see how it goes…

That being said, I suspect everything will be back in order after some future system update, and I would not be surprised that a system upgrade to 24.10 will “solve” it if not before. Despite being on another platform and with another emulator, I can’t help thinking it’s related to what Shapeshifter users experienced on Amiga…

**Comment by NovHak-Linux** [comment]
For some reason yet to be clarified, it works again. I’m only posting today, but I tried last sunday (2024-09-22) around 14:00 UTC and it did work already. Still works today. I’m curious to know if it works on your side, which would tend towards either a time-related problem, or a system update. I will have to check what updates have been done recently, but apart from that, the only thing I can think of is that I was away from home for three days, and my computer was off during that period.

Concerning a time-related problem btw, I tested that way too, by preloading a DLL that was replacing time-related glibc calls (hence intercepting system + VDSO calls), here’s the code I wrote (it didn’t change anything in the end, but I’m providing it anyway) :

```C
#include <stdbool.h>
#include <dlfcn.h>
#include <time.h>
#include <sys/time.h>

bool libload=false,cgtload=false,getdload=false,tload=false;
int (*getd)(struct timeval *restrict,struct timezone *restrict);
int (*cgt)(clockid_t,struct timespec*);
time_t (*tt)(time_t *);
void *lib;

time_t time(time_t *tloc)
{
  if (!tload)
    {
      if (!libload)
	{
	  lib=dlopen("libc.so.6",RTLD_LAZY);
	  libload=true;
	}
      *(void **)(&tt)=dlsym(lib,"time");
      tload=true;
    }
  return (*tt)(tloc)-1726041546;
}

/*
int clock_gettime(clockid_t clockid,struct timespec *tp)
{
  struct timespec tms;
  int ret;

  if (!cgtload)
    {
      if (!libload)
	{
	  lib=dlopen("libc.so.6",RTLD_LAZY);
	  libload=true;
	}
      *(void **)(&cgt)=dlsym(lib,"clock_gettime");
      cgtload=true;
    }
  ret=(*cgt)(clockid,tp);
  tp->tv_sec=tms.tv_sec-1726041546;
  //  tp->tv_nsec=tms.tv_nsec-1726041546000000000;
  return ret;
}

int gettimeofday(struct timeval *restrict tv,void *restrict tz)
{
  int ret;

  if (!getdload)
    {
      if (!libload)
	{
	  lib=dlopen("libc.so.6",RTLD_LAZY);
	  libload=true;
	}
      *(void **)(&getd)=dlsym(lib,"gettimeofday");
      getdload=true;
    }
  ret=(*getd)(tv,tz);
  tv->tv_sec-=1726041546;
  //  tv->tv_usec-=2592000000000;
  return ret;
}
*/
```

To be compiled with :
```sh
gcc -shared -fPIC -o time.so time.c
```

And being used this way :
```sh
LD_PRELOAD=./time.so ./BasiliskII-x86_64.AppImage
```

Functions to be replaced can be uncommented as needed. In the case of B2, `time()` turned out to be the one to replace. This is a rather lazy piece of code, since it does offset time by a fixed, hardcoded amount ; it would obviously be better to provide a more dynamic way, e.g. with an environment variable, as well as an option to specify an absolute date.

Everyone is free to use and modify, without necessarily mentioning me, provided it’s not being used to end the world.

**Comment by kanjitalk755** [comment]
I tried Civ II today and worked fine.
The system has been updated since the last time I tried it.

**Comment by NovHak-Linux** [comment]
OK, so that’s not Ubuntu-specific ! It would be interesting to know if people on a non-debian distro, e.g. Arch, would be similarly affected.

I’m trying to apply the rule of testing Civ II after each system update, but it’s possible that I forgot after the last one, so I can’t rule out something related to the updates… but if it’s not update related, apart from time, what could it be ?

**Comment by kanjitalk755** [comment]
Closed due to loss of reproducibility.

**Comment by NovHak-Linux** [comment]
Fwiw, it’s been crashing again since at least the 16th of october, in the same way as before (CHK error).

I have a theory about this : the crashing / non crashing periods have a fixed duration. It switches following a cycle of less than a month, around four weeks maybe, e.g. four weeks crashing, four weeks OK. That means it’s not related to system updates, and be consistent with [a similar old Shapeshifter problem](https://eab.abime.net/showthread.php?t=82897&page=2) where no sure cause for the sudden crash could possibly be identified, while it was working before (start reading from post #40).

Considering it’s been crashing since the 16th at least, according to my theory, things will get « back in order » before the 16th of november. Place your bets gentlemen !

I’m still using Ubuntu 24.04 for now, but planning to upgrade early november.

**Comment by NovHak-Linux** [comment]
I tested a few minutes ago, and it works again ! Before the 16th, as I expected… and before the 8th of december, if my theory holds true, it will start failing again.

But of course, this is valid only if you confirm it works again on your side.

I upgraded from Ubuntu 24.04 to 24.10 on the 5th of november, but I tested just before the upgrade and just after, and witnessed no change. Since then, the only thing I changed that may be remotely worth noticing that I know of, is switch from the `nvidia-driver-560` to the `nvidia-driver-560-open` metapackage, and I’m not using it anyway (modules not loaded, card not used)… so it’s probably not relevant, but I feel somehow compelled to mention anything that constitutes a system update.

Btw, I was still using version 2024-08-11 of the [AppImage releases](https://github.com/Korkman/macemu-appimage-builder/releases) and just updated to 2024-10-11, with no change. I’m not using the continuous release, so that there’s no ambiguity about which version I use.

**Comment by kanjitalk755** [comment]
I tried it now and worked fine.
Apparently, there is no doubt that this is a bug related to date.
However, it is puzzling that this problem only occurs in the Linux version.
The current date/time is obtained using the same function (localtime) regardless of the host type.

**Comment by NovHak-Linux** [comment]
I tried intercepting the `time()` system call before to set the time back in the past, and indeed the guest OS reacted accordingly, but it didn’t change anything : Civ2 was still crashing, despite `time()` returning a value in a timeframe where it was able to run. So I’m assuming it’s time-related, but not related to the functions used to retrieve time…

There are reasons to think the problem was already present in Shapeshifter on Amiga, and a workaround back in the day was to change the system time. I strongly suspect it would work here on Linux too, but am definitely not keen on having the clock set to arbitrary values on my actual system… I’m considering setting up a virtual machine to test that hypothesis.

**Comment by robxnano** [comment]
I've managed to measure the length of the periods of crashing. The results are very interesting.
```
Aug 23 2024 - Sep 16 2024: doesn't work
Sep 17 2024 - Oct 11 2024: works
Oct 12 2024 - Nov  5 2024: doesn't work
Nov  6 2024 - Nov 30 2024: works
```

Length of non-working period (~15 second precision):
Oct 12 2024 09:12:19 (1728724339 Unix time) - Nov 6 2024 05:43:37 (1730871817)
In seconds:
1730871817 - 1728724339 = 2147478

That value looks very similar to INT_MAX:
2^32 - 1 = 2147483647

If you divide by 1000, accounting for the imprecision of my measurements, the two values are practically identical!
2147483647 / 1000 - 2147478 = 5.647

Based on these results, I would say you should be looking for an integer overflow bug in a function which measures time in milliseconds.

**Comment by kanjitalk755** [comment]
This is a very interesting discovery.
There seems to be a problem in timer_unix.cpp, but I haven't found it so far.

**Comment by NovHak-Linux** [comment]
Very interesting indeed. Maybe comparing with Shapeshifter code would help, since as I mentioned before, this very much looks like what some people experienced on Amiga…

There’s a small mistake though, it’s 2^31, not 2^32 !

That being said, I guess I don’t need to set up a VM any more, and I’m preparing myself for the upcoming failure around Sun Dec  1 02:15:00 UTC 2024.

I wonder if it’s timezone-dependent.

**Comment by NovHak-Linux** [comment]
Workaround found ! (apart from changing system time that is)

I posted some code in [a previous post](https://github.com/kanjitalk755/macemu/issues/206#issuecomment-2371636361), that I used to intercept time-related system calls. I’m glad I gave it a second view, because it contained a silly error.

So finally, it turns out redirecting `clock_gettime()` and get back in time by 2^31/1000 seconds works pretty well ! As a bonus, it doesn’t even change the guest OS time. And I know that when C2 will stop working again, I’ll just have to stop offsetting `clock_gettime()`.

Hopefully, it will help narrow the search.

Here is the code :
```C
#include <stdbool.h>
#include <dlfcn.h>
#include <time.h>
#include <sys/time.h>

bool libload=false,cgtload=false;
int (*cgt)(clockid_t,struct timespec*);
void *lib;

int clock_gettime(clockid_t clockid,struct timespec *tp)
{
  int ret;

  if (!cgtload)
    {
      if (!libload)
	{
	  lib=dlopen("libc.so.6",RTLD_LAZY);
	  libload=true;
	}
      *(void **)(&cgt)=dlsym(lib,"clock_gettime");
      cgtload=true;
    }
  ret=(*cgt)(clockid,tp);
  tp->tv_sec-=2147483;
  return ret;
}
```

As before, compile with :
```sh
gcc -shared -fPIC -o time.so time.c
```

And use like this :
```sh
LD_PRELOAD=./time.so ./BasiliskII-x86_64.AppImage
```

**Comment by rakslice** [comment]
Quickly adding `printf`'s to all the `clock_gettime()` users, I see `Microseconds()` is getting called a number of times right when Civ II launches.
https://github.com/kanjitalk755/macemu/blob/96e7f8566c7ebc6ff083707c2da022e1a1ab6628/BasiliskII/src/Unix/timer_unix.cpp#L54
It's probably just overflowing something internally that is not expecting the crazy values the implementations other than `__MACH__` there are returning.

**Comment by rakslice** [comment]
But I am curious if the implementation here where the result is being returned in `A0` and `D0` is right.
https://github.com/kanjitalk755/macemu/blob/96e7f8566c7ebc6ff083707c2da022e1a1ab6628/BasiliskII/src/emul_op.cpp#L237
I don't see the actual `_Microseconds` trap documented anywhere and what documentation there is for the function is more consistent with there being a 4-byte memory record holding the result
https://dev.os9.ca/techpubs/mac/OSUtilities/OSUtilities-103.html#MARKER-9-111

https://vintageapple.org/inside_r/pdf/Operating_System_Utils_1994.pdf#page=219

**Comment by rakslice** [comment]
Oh, I see, the trap is usually being used as part of a short routine in the header that loads the `A0` and `D0` values into a record
https://github.com/kasper93/mpc-hc/blob/185bd36e6cba5512c4d6fd95cf05ba135582d0e8/include/qt/Timer.h#L210

```
00000000 : 225f                MOVEA.L  (A7)+,A1
00000002 : 22c8                MOVE.L   A0,(A1)+ 
00000004 : 2280                MOVE.L   D0,(A1) 
```

**Comment by Korkman** [comment]
Was watching this, here's fresh builds

https://github.com/Korkman/macemu-appimage-builder/releases/tag/continuous

**Comment by NovHak-Linux** [comment]
Wonderful ! I for one wouldn’t have expected this bug to be solved between christmas and new year’s eve 😁

Thank you all for helping, and @rakslice for giving the final blow !
