### ISSUE TITLE
GTK3: Custom resolutions reset when opening the GUI

### ISSUE THREAD

**Issue by prurigro** [kanjitalk755/macemu#207]
If you set a custom resolution either in .basilisk_ii_prefs or the gui and save, launching the VM will run in the chosen resolution correctly. Starting BasiliskII without a gui will continue to observe the chosen resolution, but if you start with the gui enabled the custom resolution will be reset to the maximum option.

This is with the new GTK3 GUI (which is otherwise great btw!)

Let me know if you need more detail, and thanks for maintaining this software!

**Comment by kanjitalk755** [comment]
I tried it in the following environment, but it did not reproduce.

Debian 12.7
libgtk-3-dev 3.24.38

**Comment by prurigro** [comment]
@kanjitalk755 Hey, sorry about the delay in getting back to you. I'm not sure what changed, but this seems to be resolved now. So either a recent commit fixed it, or I was triggering the issue in some other more obscure way that's no longer the case.

Either way, thanks again for everything!
