### ISSUE TITLE
Compiling From Source On Fedora Workstation Produces 'fatal error: SDL.h: No such file or directory' Error

### ISSUE THREAD

**Issue by SamuelBanya** [kanjitalk755/macemu#211]
I followed the steps in the following link:
- https://www.emaculation.com/doku.php/compiling_sheepshaver_basilisk#building_basiliskii_and_sheepshaver_in_linux

The related commands for installing BasiliskII include the following:
```
git clone https://github.com/kanjitalk755/macemu
cd macemu/BasiliskII/src/Unix
NO_CONFIGURE=1 ./autogen.sh
./configure --enable-sdl-video=yes --enable-sdl-audio=yes --with-bincue
make
strip BasiliskII
```

I ran the commands up to the 'make' command and received an error.

Related error:
```
sam@fedora ~/hub/applications/macemu/BasiliskII/src/Unix (master)$ make
g++ -DBINCUE -I./../include -I./. -I. -I./../CrossPlatform -I./../uae_cpu -I./../slirp -DHAVE_CONFIG_H  -DOS_linux -DBINCUE -DDIRECT_ADDRESSING -DUNALIGNED_PROFITABLE -DX86_64_ASSEMBLY -DOPTIMIZED_FLAGS -DUSE_JIT -DUSE_JIT_FPU -DFPU_IEEE -D_REENTRANT -DDATADIR=\"/usr/local/share/BasiliskII\" -g -O2 -fno-merge-constants -fno-gcse-sm -fwrapv  -c ./../CrossPlatform/video_blit.cpp -o obj/video_blit.o
./../CrossPlatform/video_blit.cpp:26:10: fatal error: SDL.h: No such file or directory
   26 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:200: obj/video_blit.o] Error 1
```

This still happens after I installed the 'SDL2-devel' and 'SDL-devel' packages from Fedora's 'dnf' package manager for SDL2, and SDL1 with these commands:
```
sudo dnf install SDL2-devel
sudo dnf install SDL-devel
```

Any ideas on how to fix this issue? Should the makefile be modified accordingly?

Thanks.

**Comment by kanjitalk755** [comment]
When compiling, the arguments are reflected the result of the following command.

```
pkg-config sdl2 --cflags
```

On Debian it looks like this:

```
-I/usr/include/SDL2 -D_REENTRANT
```

If this is not correct you will get an error like your post.

**Comment by robxnano** [comment]
I think you need to re-run the configure step after installing SDL2-devel.
