### ISSUE TITLE
Adding new values for 'mag_rate'  parameter. Scaling.

### ISSUE THREAD

**Issue by Farooq87** [kanjitalk755/macemu#212]
Could you please extend 'mag_rate' number of values for future releases of emulator?
It is much needed to enlarge/scale window with set resolution in emulated OS.
I need to keep 640x480 resolution as it is, but scale size of Sheepshaver's window as I prefer.
There are some standard values in preferenes of 'mag_rate'  parameter: 1,2,3. All above 1 will scale window but 2 is too large.
What I suggest is an ability to set some values in between 1 and 2
1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9 

This is enlarged Sheepshaver's window with 'mag_rate 2' (640x480). 1 is too small, 2 is too large.
![image (1)](https://github.com/user-attachments/assets/3a964cde-b0e4-4003-9e85-f699ea6ccc16)

**Comment by kanjitalk755** [comment]
Implemented.

**Comment by kanjitalk755** [comment]
Of course I considered about that method when implementing window enlargement.

> To click on the edge of the emulator, hold cursor and stretch to any height/width as you wish.

However, I didn't like that I could unintentionally resize the window by dragging near the edge of it.
Therefore, I adopted the current specification of specifying the magnification rate using prefs instead.

**Comment by emendelson** [comment]
Yes, the way it works is best. Please do NOT allow dragging the window. It is far too easy to get it wrong. When I build DOSBox, I always disable the ability to resize an existing window. It is very good that macemu does NOT allow resizing by dragging.

**Comment by kanjitalk755** [comment]
Functionally, `mag_rate` is sufficient, so there is no plan to implement it.

**Comment by Farooq87** [comment]
> Functionally, `mag_rate` is sufficient, so there is no plan to implement it.

Ok. BIG THANKS for extending `mag_rate`
