### ISSUE TITLE
Unable to detect audio device on linux

### ISSUE THREAD

**Issue by MirandaStreeter** [kanjitalk755/macemu#216]
From compiled latest on Linux (arch), I see the following:

```
[<user>@<hostname> Unix]$ sudo /opt/SheepShaver/SheepShaver 
[sudo] password for miranda: 
SheepShaver V2.5 by Christian Bauer and Mar"c" Hellwig
Using prefs file at /root/.sheepshaver_prefs
Reading ROM file...
WARNING: Cannot open audio: ALSA: Couldn't open audio device: Host is down
selected Ethernet device type slirp
Using SDL_Renderer driver: opengl
Detected CPU features: MMX SSE SSE2 SSE3 SSSE3
PowerPC CPU emulator by Gwenole Beauchesne
WARNING: Unknown DiskStatus(6)
WARNING: Unknown DiskStatus(6)
```

The `Cannot open audio: ALSA: Couldn't open audio device` is combined with a popup message:
![image](https://github.com/user-attachments/assets/fe00a833-472c-4101-a15c-fe29e7c4bcad)
I see the same exact behavior for Basilisk. I can't get audio to play despite everything else indicating it should work fine.

My question is how does it detect the system's audio device? Is it doing something unique?

I ask because I have `pipewire` and `pipewire-alsa` v1.2.6 installed which should act as a drop-in compatibility layer. All applications using the ALSA API should be routed through PipeWire. I can verify the ALSA shim works fine as I mess around with `aplay`.

"Enable Sound Output" is checked. I'm aware the GUI is a red herring - oss isn't used and `/dev/dsp` is ignored. Other SDL2 applications work fine in my experience.

If I'm overlooking something obvious then don't be afraid to let me know.

**Comment by robxnano** [comment]
I think I've found the cause of the original problem. The pipewire-alsa library tries to connect to the socket `$XDG_RUNTIME_DIR/pipewire-0`, which works as a normal user but not under root as the environment variable isn't set. The easy solution would be to use `sudo -E` but this results in a warning from PulseAudio (and causes other issues such as using the wrong theme and font in the UI):
```
XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
```
Alternatively, `sudo PIPEWIRE_RUNTIME_DIR=$XDG_RUNTIME_DIR ./SheepShaver` seems to work without any warnings, on Ubuntu at least. On Fedora, however, running as root worked perfectly, as it had set up a dedicated `XDG_RUNTIME_DIR` for the root user, complete with its own PipeWire socket.

**Comment by kanjitalk755** [comment]
SheepShaver's JIT compiler requires the same memory map as the guest OS, including the zero page.
By disabling the JIT compiler, you can offset the entire memory map and no longer need to map the zero page.

```
./configure --disable-jit --enable-addressing=direct,0x10000000
```
