### ISSUE TITLE
Raspberry Pi 5 ERROR: Cannot map usable RAM area. Try to decrease the MacOS RAM size.

### ISSUE THREAD

**Issue by vaccinemedia** [kanjitalk755/macemu#219]
After building as per the instructions and also running sudo make install after running make and then copying the executable to a separate folder containing the new world rom I'm seeing after running sudo ./SheepShaver:
ERROR: Cannot map usable RAM area. Try to decrease the MacOS RAM size.

**Comment by kanjitalk755** [comment]
I can't verify it with RPi5, but how about the following config?

```
./configure --enable-addressing=direct,0x10000000
```

**Comment by vaccinemedia** [comment]
If I try that I get the following:
checking for addressing mode to use... configure: error: could not determine a sensible NATMEM_OFFSET value

**Comment by vaccinemedia** [comment]
I managed to get it running but without a settings GUI by running:
NO_CONFIGURE=1 ./autogen.sh
./configure --enable-sdl-video --enable-sdl-audio --disable-vosf --disable-jit

So maybe it had something to do with the other necessary configure flags? If so I think we need some separate build instructions for the Pi.

My only issue now is launching to the options GUI instead of straight to a mac screen with a question mark floppy so if there's a way of making this happen that would be amazing and very much appreciated! :D

**Comment by kanjitalk755** [comment]
Have you installed GTK?

```
sudo apt install libgtk-3-dev
```

Once installed, start over from configure.

```
./configure --disable-jit
```

The following arguments are defaults, so I would like to confirm that they work without them.

```
--enable-sdl-video --enable-sdl-audio --disable-vosf
```

**Comment by vaccinemedia** [comment]
@kanjitalk755 installing GTK did the trick and it now has the GUI when starting. I should have mentioned that to get it working without the GUI earlier I had to hard code the values in configure.ac for 0x10000000 so it looks like:

`  if AC_TRY_EVAL(doit); then
    NATMEM_OFFSET=0x10000000
  else
    NATMEM_OFFSET=0x10000000`

**Comment by vaccinemedia** [comment]
Re-opening because of the issue that still exists which is when setting the --enable-addressing=direct,0x10000000 flag the error which appears:
checking for addressing mode to use... configure: error: could not determine a sensible NATMEM_OFFSET value

So the source needs to be modified to use the flag so it's either a bug which needs fixing or the modification needs to be in the readme file under a heading for the Raspberry Pi OS

**Comment by kanjitalk755** [comment]
Could you submit a PR?

**Comment by vaccinemedia** [comment]
If I did the PR would contain hard coded values of 0x10000000 which may break the compile for people who are sending in other values in the flag.
