### ISSUE TITLE
Myst - Error number t107 occurred.

### ISSUE THREAD

**Issue by reedlove** [kanjitalk755/macemu#220]
When emulating on Basilisk II with System 7.5.5 as a Macintosh IIci, Myst craps out with the t107 error.
![Screenshot from 2024-12-05 19-15-45](https://github.com/user-attachments/assets/2b1e9313-d6a4-461c-a6ba-f334cdc30a83)

Trying to figure this out, I found the following forum thread:
https://www.emaculation.com/forum/viewtopic.php?t=5951

Apparently it has something to do with volume settings in PRAM. Just as mentioned in the thread, if you adjust the system volume before running Myst there are no errors. XP

**Comment by kanjitalk755** [comment]
There seems to be no volume setting in XPRAM.

https://okmij.org/ftp/xPRAM.html

**Comment by reedlove** [comment]
I guess originally someone on the thread assumed that the volume level was being saved to PRAM.

Here's more information regarding the bug:

"Myst has a line of HyperTalk that attempts to add a check mark to the appropriate menu item in its "Volume" menu. It bases this off of the result returned by an XFCN, xGetSoundVol() which it quite reasonably expects to return an integer between 0 and 7 inclusive.

However, in Basilisk II, something goes wrong under the hood after the system starts up, and this function return 255. This seems to be the case every time the system boots, regardless of what the system volume was set to previously. And naturally this causes Myst to reference a menu item that does not exist, hence error t107."

"255 is also known as "-1" and is signaling that there is no audio interface on which to get a sound volume. Myst is assuming that there is always audio hardware present and that it is selected; Basilisk II requires you to select a device before it will return anything."

**Comment by kanjitalk755** [comment]
> However, in Basilisk II, something goes wrong under the hood after the system starts up, and this function return 255.

Please tell me how to check this value.

**Comment by reedlove** [comment]
So I've done some comparative analysis between Basilisks PRAM behavior and qemu's q800 PRAM.

On Basilisk II, changing the volume does nothing to the PRAM data.
![basiliskii-pram](https://github.com/user-attachments/assets/7ef0efb9-f18d-448c-aa08-a465ee663e88)

On QEMU, changing the volume changes the value of the byte at offset 0x8.
QEMU - Full Volume = 0x17
![qemu-pram-full_volume](https://github.com/user-attachments/assets/ad50499d-7e6c-48cb-8e66-7f95eba11047)
QEMU - Lowest Volume = 0x10
![qemu-pram-lowest_volume](https://github.com/user-attachments/assets/12bccbe7-eaeb-48e3-b622-dcc6c2a9cdb9)

**Comment by kanjitalk755** [comment]
Thank you for this important information.
I tried implementing it.

https://github.com/kanjitalk755/macemu/tree/fix_220

**Comment by reedlove** [comment]
So I compiled it and tested it. While it does show that the speaker volume level is being saved, Myst still errors out unless I open the speaker volume control first.
Even though the value is getting saved, is it being passed to the hardware before Mac OS boots?

**Comment by kanjitalk755** [comment]
> Even though the value is getting saved, is it being passed to the hardware before Mac OS boots?

Yes, the volume value stored in XPRAM is set in InitAll() before starting emulation.

**Comment by reedlove** [comment]
Unfortunately I don't know anything about the low level details regarding how a 68k Mac initializes it's hardware and restores anything from pram. The only other thought that I have is that the sound hardware is not initialized prior to the volume setting being read from PRAM. Perhaps the reason why it still shows the saved value in Mac OS is because the value is read from PRAM when the control panel is opened?

**Comment by kanjitalk755** [comment]
After audio initialization, XPRAM is read and set the speaker volume based on that value.

https://github.com/kanjitalk755/macemu/blob/4cc13339391ac148a9fefd78d02b2d37cfcf6098/BasiliskII/src/main.cpp#L170-L174

No further changes will be made to the volume from the host side.
