### ISSUE TITLE
missing binary operator before token "(" on Raspberry 5

### ISSUE THREAD

**Issue by aminta** [kanjitalk755/macemu#222]
Hi, just tried to build SheepShaver on Raspberry 5 64 Bit, I get this error message at `sudo make`:

```
g++ -I../kpx_cpu/include -I../kpx_cpu/src -I../include -I. -I../CrossPlatform -I../slirp -DHAVE_CONFIG_H -D_REENTRANT -DDATADIR=\"/usr/local/share/SheepShaver\" -g -O2  -c main_unix.cpp -o obj/main_unix.o
main_unix.cpp:923:46: error: missing binary operator before token "("
  923 | #if SDL_PLATFORM_MACOS && SDL_VERSION_ATLEAST(2,0,0)
      |                                              ^
make: *** [Makefile:206: obj/main_unix.o] Error 1
```

**Comment by kanjitalk755** [comment]
Is `libsdl2-dev` installed correctly?

**Comment by aminta** [comment]
Thanks, it works, but SheepShaver keeps to output the error `ERROR: Cannot map usable RAM area. Try to decrease the MacOS RAM size.` even with low (eg: 16MB) RAM memory values in config....

**Comment by RonaldPR** [comment]
This is a known issue with SheepShaver. It uses a specific and contiguous place in memory that may be occupied by other processes. Did you try restarting the host and then start SheepShaver first thing?

**Comment by aminta** [comment]
> This is a known issue with SheepShaver. It uses a specific and contiguous place in memory that may be occupied by other processes. Did you try restarting the host and then start SheepShaver first thing?

“First thing” do you mean restart in CLI and start SheepShaver straightaway?

**Comment by RonaldPR** [comment]
I mean: Restart your host machine and then start SheepShaver before starting other software.

**Comment by aminta** [comment]
https://github.com/user-attachments/assets/a5e5c566-42fc-4887-9b03-031503aa35f8
![IMG_5110](https://github.com/user-attachments/assets/97e26ec3-468b-4618-be6b-e949965f08b0)
![IMG_5111](https://github.com/user-attachments/assets/c1fe3d31-6a8c-4e32-8694-19eec94e2d85)

**Comment by aminta** [comment]
Just tried to autoload at login launching from `rc.local`:

```
Wed Dec 25 04:30:14 PM CET 2024: powerpc ----------
ERROR: ld.so: object '/usr/\1039LIB/pulseaudio/libpulsedsp.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
SheepShaver V2.5 by Christian Bauer and Mar"c" Hellwig
WARNING: Unknown preferences keyword 'modelid'
WARNING: Unknown preferences keyword 'fpu'
WARNING: Unknown preferences keyword 'jitfpu'
WARNING: Unknown preferences keyword 'jitdebug'
WARNING: Unknown preferences keyword 'udptunnel'
Using prefs file at /usr/share/macintoshpi/powerpc/powerpc.cfg
ERROR: Cannot map usable RAM area. Try to decrease the MacOS RAM size.
```

**Comment by aminta** [comment]
Ok I've managed to make it work building from [this fork](https://github.com/vaccinemedia/macemu) (see also: https://www.emaculation.com/forum/viewtopic.php?p=79962&hilit=ERROR%3A+Cannot+map+usable+RAM+area#p79962) but it works only in X and I need it to make it work from CLI...

**Comment by aminta** [comment]
Ok, figured out, you have to build your own version of SDL2 with X11 disabled: `--disable-video-x11`. Fixed (but only using the linked fork so I'm leaving this thread opened).

**Comment by kanjitalk755** [comment]
I've added the link to the fork you mentioned to `README.md`.
I'm unable to test the binaries on RPi5 so this fork does not support it.
