### ISSUE TITLE
Request: Enable wiki functionality for this repo

### ISSUE THREAD

**Issue by adamhope** [kanjitalk755/macemu#223]
Hi,

Would you mind enabling the wiki functionality for this repo so we can keep information like configuration options with the code so that we don't have to cross reference other sites like emaculation?

I'm aware that the cebix/macemu repo has it enabled but this fork seems to be the most active version of Basilisk ii.

**Comment by kanjitalk755** [comment]
I think it would be better to aggregate usage information on Emaculation.
GitHub wikis are in different locations with each new developer, so the information becomes fragmented.

**Comment by adamhope** [comment]
Unfortunately it looks like there is no easy way to collaborate on the wiki:

"E-Maculation Wiki

There is no open registration with this wiki. Only administrators and assigned editors can post or edit articles."

What would you suggest?

**Comment by RonaldPR** [comment]
The number of people that can edit articles in Emaculation wiki is intentionally limited. That wiki is about established information like manuals, not intended for cooperation.
Emaculation forum, however, is about collaboration. It is full of information and discussions about issues and developments. The forum is not only for user support but also for developers discussing their work.
