### ISSUE TITLE
Build fails for non-X11 GTK

### ISSUE THREAD

**Issue by rakslice** [kanjitalk755/macemu#29]
Building fails on Mac OS X with GTK present.

```
main_unix.cpp:136:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^~~~~~~~~~~~
2 warnings and 1 error generated.
make: *** [obj/main_unix.o] Error 1
```

GTK was detected by autotools and the GTK GUI was enabled automatically, but the GTK it found is Quartz-based, not X11 based; the system does not have X11 by default.

**Comment by kanjitalk755** [comment]
Considering GTK1.2, if it is neither QUARTZ nor WAYLAND, it is determined that X is used.

Please test:
https://github.com/kanjitalk755/macemu/tree/test_notX

**Comment by rakslice** [comment]
I've tested that this builds and runs:
- Debian 10 i386 with gtk2/sdl2
- Mac OS X 10.12 with gtk2/sdl2
- Debian 10 i386 with gtk 1.2.x/sdl2

I don't have a practical non-linux platfrom I know how to do a gtk 1.2.x build on

**Comment by kanjitalk755** [comment]
It seemed to be OK, so I merged it to the master.
