### ISSUE TITLE
Crash when moving to second item in Scrapbook

### ISSUE THREAD

**Issue by MrMacvos** [kanjitalk755/macemu#3]
Hi,

Great work, what you're doing!
I have an issue with both Ronald's and your version 2.4 of Sheepshaver: when you open the Scrapbook from the Apple-menu, and click the right-arrow to move to the second item, Sheepshaver crashes.

(I'm running Sheepshaver on an iMac, HFS+ 2TB SSD, 32GB RAM and macOS High Sierra 10.13.4)

[SheepShaver_2018-04-09-100653_IMAC2012.crash.txt](https://github.com/kanjitalk755/macemu/files/1888951/SheepShaver_2018-04-09-100653_IMAC2012.crash.txt)

**Comment by kanjitalk755** [comment]
This bug has not been reproduced on my environment.
Host: macOS High Sierra 10.13.4
Client: Mac OS 8.6

Please try to make "Ignore Illegal Instructions" of preference ON.

**Comment by MrMacvos** [comment]
Yes, that did it.
Thanks!

- -
Marc
