### ISSUE TITLE
Some files on the 'make links' list also have different checked in versions in SheepShaver

### ISSUE THREAD

**Issue by rakslice** [kanjitalk755/macemu#32]
In the course of working through what is necessary to build BasiliskII and SheepShaver with GTK prefs app in mingw32, when dealing with the Windows git working copy's placeholder files for symlinks to properly do `make links`, I found that some of the files present were not placeholder files at all but were already existing source files.

The files:
- `src/CrossPlatform/sigsegv.cpp`
- `src/Unix/Darwin/lowmem.cpp`

are on `SheepShaver/Makefile`'s list of files to symlink from `BasiliskII` to `SheepShaver` in `make links`, as well as already present as a checked in file in `SheepShaver`.

These should presumably be removed from the list in `make links`, or else if the checked in changes in `SheepShaver` are unwanted they should be removed from `SheepShaver` and symlinks to `BasiliskII` checked in in place for the platforms that do not ordinarily need `make links`.

**Comment by rakslice** [comment]
Just so it's clear, I should note that the checked in files I'm referring to in `SheepShaver` are different than the `BasiliskII` ones, they're not just duplicates.

**Comment by kanjitalk755** [comment]
Deleted sigsegv.cpp and lowmem.c from list of "make links".
