### ISSUE TITLE
do_frsqrte implementation is missing

### ISSUE THREAD

**Issue by rakslice** [kanjitalk755/macemu#36]
`ppc-dyngen-ops.cpp` has a `DEFINE_OP` entry that refers to `do_frsqrte`, but there is no `do_frsqrte` macro present

**Comment by rakslice** [comment]
Maybe this got lost somewhere and, since almost no one does the dyngen, no one noticed?

**Comment by kanjitalk755** [comment]
This line was added by #20.
Is it insufficient?

**Comment by rakslice** [comment]
Unfortunately yes. But the function it would create, `op_frsqrte_FD_F0`, also wasn't used, so it could just be taken out, as I did in #37.
