### ISSUE TITLE
SS Windows "keycodes true" (but no keycode file) produces warning

### ISSUE THREAD

**Issue by emendelson** [kanjitalk755/macemu#38]
In the latest code, if I launch SheepShaver for Windows with a prefs file that has "keycodes true" but no keycodefile listed, a warning appears:

> Cannot open keycode translation file BasiliskII_keycodes (No such file or directory).

Should this appear at all? And shouldn't it say SheepShaver_keycodes, now that the file has changed its name?

**Comment by kanjitalk755** [comment]
Fixed by ecef51b.

**Comment by kanjitalk755** [comment]
The default keycodes file name has been changed as follows for compatibility from before.
BasiliskII:  BasiliskII_keycodes
SheepShaver: keycodes
