### ISSUE TITLE
Param to select SDL renderer

### ISSUE THREAD

**Issue by rakslice** [kanjitalk755/macemu#41]
It would be useful to have a prefs parameter to select which SDL renderer to use, for when it is necessary to override it because the default option has problems.

Curiously, `SDL/prefs_sdl.cpp` already has such a parameter, it just isn't hooked up to anything.

That part of https://github.com/DavidLudwig/macemu/commit/1eb824a04eec1bd947454eeea528edf07f08b955 was perhaps removed but not replaced with anything.

**Comment by kanjitalk755** [comment]
Fixed.
