### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by lmartinking** [kanjitalk755/macemu#5]
Hi @kanjitalk755 I just want to give you a huge thanks -- I have built both Basilisk II and SheepShaver on MacOS as 64-bit builds and they run significantly better than some older builds I have. 😄 

I'm not sure what your process for debugging is, but I am more than happy to send you information if you give me some pointers to the best method (`lldb` core dump?)

**Comment by kanjitalk755** [comment]
First, check the following items of ~/.sheepshaver_prefs.

ignoresegv true
ignoreillegal true

If SheepShaver crashes even if this setting used, paste the backtrace parts of the crash report here.
And tell me the crash situation (application and operation).
If I can reproduce the problem, it's easier to debug.
