### ISSUE TITLE
Latest BII code won't build in Xcode under Mojave or Catalina

### ISSUE THREAD

**Issue by emendelson** [kanjitalk755/macemu#53]
Hello, with current code, builds of BII fail under Xcode with this message:

clang: error: no such file or directory: '/Users/edward/Library/Developer/Xcode/DerivedData/BasiliskII-cpozzywkzeiuxuazxfpwpsojbaeg/Build/Products/Release/gencpu_output/defs68k.c'
clang: error: no input files

SheepShaver builds successfully, but not BasiliskII.

**Comment by kanjitalk755** [comment]
Fixed.
