### ISSUE TITLE
Gamma ramp adjusts entire display

### ISSUE THREAD

**Issue by spolsley** [kanjitalk755/macemu#54]
As of ffee1eba, support for passing through guest gamma settings was added via SDL_SetWindowGammaRamp.  I very much like the additional feature and support for guest OS controls; however, it can cause noticeable display flickering when alternating between SheepShaver and other applications, especially in windowed mode.  I found screen recordings don't capture the change but recorded a brief demonstration with an external camera:

![gamma_change](https://user-images.githubusercontent.com/5054223/92832004-baa45100-f39c-11ea-942c-a32f3baefd76.gif)

Strangely, [SDL's wiki](https://wiki.libsdl.org/SDL_SetWindowGammaRamp#Remarks) states this is intended behavior:

```
Despite the name and signature, this method sets the gamma ramp of the entire display, not an individual window.
```

---

If anybody else is experiencing this, I'm wondering about a couple options:

1. Ideally, an SDL function to apply gamma settings to the window.  I'd guess displays can't do this in hardware, so it'd have to be a software remedy, but it may prove too difficult or computationally intensive to be practical.  I haven't found such an API in SDL yet.

2. Adjusting the guest OS gamma level.  I don't see any gamma controls in the native Monitor settings and will search for a utility on Macintosh Garden, but it may be functionality to implement in Sheepshaver since it provides the virtual display.

3. Perhaps an option to disable the gamma passthrough, at least in window mode.  I don't think it'll be noticeable in fullscreen to anyone but do worry about it being potentially distracting when using windowed mode on some displays.

**Comment by spolsley** [comment]
A couple more observations:

Regarding point 2, I found [Thomas Knoll's Gamma](https://macintoshgarden.org/apps/gamma) tool can help.  It allows me to nearly match my Mac visually, but Night Shift is problematic.  The changing white point on the host leads to increasing divergence with the guest.

In further testing, it seems that changing resolution in the guest breaks the gamma setting.  Also, games like [Ferazel's Wand](https://macintoshgarden.org/games/ferazels-wand) that make extensive use of gamma operations aren't behaving as expected, with the screen fading to black and not returning.

I'm leaning towards trying a preference item, something like "gammaramp" with options `off`, `fullscreen`, or `always`.  Although the fade-to-black and not returning problem may be a bug.

**Comment by kanjitalk755** [comment]
> I'm leaning towards trying a preference item, something like "gammaramp" with options off, fullscreen, or always. Although the fade-to-black and not returning problem may be a bug.

I tried to implement this.

**Comment by spolsley** [comment]
I'll have to pull it down and try it!  I was also just playing around with this and debugging the issue with Ferazel's Wand.

It looks like SDL's gamma ramp requires 16-bit color depth, but games like Ferazel's Wand switch to 256 colors.  So the game launches, fades to black, and then updates display settings while dark: changing resolution (if enabled) and color bit depth.  Once that change is made, line 1787 of video_sdl2 prevents future gamma updates

`if ((int)VIDEO_MODE_DEPTH > VIDEO_DEPTH_8BIT)`

so the screen stays black and is unable to raise brightness again.  Unfortunately, if SDL requires thousands of colors, it will require some work to support lower bit depths.  Probably a function mapping 8-bit to 16-bit at the very least, but I've no idea how to support custom CLUTs, which Ferazel's Wand and other games of its era used a lot.

I'm going to brainstorm alternatives.  I think it'd be possible to check if we've changed to a lower bit depth, what the current gamma level is, and just restore it to a default.

**Comment by kanjitalk755** [comment]
I think the gamma ramp is also valid even if guest is 256 colors mode.
But current implementation, `mac_pal` is used for both CLUT and the gamma ramp.
We may need to be separated tables for each other.

**Comment by spolsley** [comment]
Aha!  This is indeed the case.  So the forcing to 16-bit depth was a workaround to avoid the wonky colors that would get set once mac_pal is filled with a 256 CLUT...

I added mac_gamma in addition to mac_pal to store gamma changes, and Ferazel's Wand launches and adjusts the screen accordingly.  I think it would be better to add a separate video_set_gamma() function and have set_gamma() from video.cpp call that; it's currently making video_set_palette() handle both gamma and colors but separate functions would probably improve efficiency.  A remaining change would be to call video_set_gamma() in set_video_mode() because resolution changes are currently breaking the gamma settings.

**Comment by spolsley** [comment]
I'm testing on a [branch for gamma ramps](https://github.com/spolsley/macemu/commit/6de9a5032d2e6b5485d1fafd40c7bc8cf619cb30) with some of these changes, and it seems to remedy the issues with 256 colors, Ferazel's Wand, and changing monitor settings.  However, there are still some issues.  [EV Nova](https://macintoshgarden.org/games/escape-velocity-nova), which I believe uses 16-bit color, is stuck with brightness at about half.  It's probably tied to Ambrosia's Monitor Tool, which is notoriously difficult, but hopefully, it's just a small error.

**Comment by kanjitalk755** [comment]
I merged your `gammaramp` branch and fixed the 16-bit color issue.

**Comment by spolsley** [comment]
Yes, everything looks correct now.  I admire how quickly you can diagnose and fix these errors 😀. Any idea why passing `n_colors` works while reading it from the current mode didn't?

In any event, I'm not seeing anymore unexpected behaviors, and even though gamma still has to be set at the display level, the new prefs item resolves the issue!

**Comment by rakslice** [comment]
Is having a separate gamma table in indexed colour modes the expected behaviour of `cscSetGamma`? If so then that's a fine partial change so far...

The reason that I had SheepShaver put the gamma table through the palette and had `video_sdl.cpp` & `video_sdl2.cpp` take it from there, for the `IsDirectMode()` true case (when the emulated Mac is in > 256 colour mode), is that this followed the existing codebase -- this is where BII was putting it and where both BII and SS `video_x.cpp` implementations were taking it from.  

So for the change to break out the gamma table, the rest of the changes needed are:
- SDL 1 (essentially the same change as for `video_sdl2.cpp` applied to `video_sdl.cpp`)
- Basilisk II (in its `video.cpp` implementation of `::load_ramp_palette`, use `::set_gamma` instead of `::set_palette`)
- X11 (based on the existing problems with X11 in this fork before this change -- SDL preprocessor defines when SDL is configured off, and the pixel colour endianness problem in the resulting build -- maybe no one cares if this even builds, but for posterity I'll say: in the BII and SS `video_x.cpp`, implement `::set_gamma` and `::video_set_gamma` as copies of the palette ones, to support old school X servers where the gamma exposed by the palette API in true colour mode is even hooked up to anything)

**Comment by kanjitalk755** [comment]
@spolsley
> Any idea why passing n_colors works while reading it from the current mode didn't?

Since `palette_size` is the number of CLUTs, it is correct to use `data_cnt` in `set_gamma()` for the number of gamma tables.

@rakslice
> Is having a separate gamma table in indexed colour modes the expected behaviour of cscSetGamma?

I couldn't find the spec about `cscSetGamma`, so I guessed it from the behavior of Ferazel's Wand.
It uses indexed color mode, but uses the gamma fader without changing the CLUT.
So, by having separate tables, it started to work as expected.

> So for the change to break out the gamma table, the rest of the changes needed are:

My fork is assumed to be used with SDL2.
BasiliskII will be put on hold until the bug is reported.
Of course, pull requests are welcome.

**Comment by spolsley** [comment]
For anyone curious, I found a little detail about the `SetEntries` and `SetGamma` functions in [Apple's reference for graphics drivers](https://developer.apple.com/library/archive/documentation/Hardware/DeviceManagers/pci_srvcs/pci_cards_drivers/Designing_PCI_Cards_Drivers.pdf#page=478).  It looks like two separate tables is correct as they specify both `csTable` and `csGTable`, but the former is not used outside indexed modes.

In terms of initial implementation, even [cebix cvs](http://www.cebix.net/viewvc/cebix/SheepShaver/src/video.cpp?logsort=date&view=log&sortby=author&pathrev=MAIN) only goes back so far, not enough to show the original addition of `set_gamma` or any commit logs.  I think the joint table usage went unnoticed for years since many 256 color games don't make much use of gamma operations, but Ferazel's Wand prompted the only semi-recent work in that area.

It's really wonderful to have this new feature of gamma passthrough, plus the old implementation corrected!  I agree it may be worth porting to BII and possibly SDL1 systems, if any targets are still using that, and can help with a PR.  When I was looking through the old logs and forks, it reminded me there are many interesting features to maybe centralize someday.

**Comment by rakslice** [comment]
Ah okay. I've seen this documentation also, but I didn't understand the significance of `SetEntries` at the time. In fact in indexed modes it is expected that the guest will send these in a particular order:

> To reduce visible flashes resulting from color table changes, the SetGamma
> routine works in conjunction with the SetEntries control routine on indexed
> devices. The SetGamma routine first loads new gamma correction data into the
> driver’s private storage; the next SetEntries control call applies the gamma
> correction as it changes the CLUT. SetGamma calls are always followed by
> SetEntries control calls on indexed devices.

**Comment by kanjitalk755** [comment]
I fixed BII because a related issue is reported at Emaculation forum.
