### ISSUE TITLE
Feature request: support for multiple tap devices in Windows

### ISSUE THREAD

**Issue by cat7** [kanjitalk755/macemu#58]
Hi,

Sheepshaver and Basilisk for Windows support networking through a bridged/shared tap device when the (openvpn) tap device is installed. 
The tap device can be selected in the GUI network tab. This sets ether to tap and finds the etherguid automatically. However, I have two tap devices bridged with my default ethernet connection. I can only select one and the same tap device in the GUI.
It would be nice if Basilisk/SheepShaver would list all tap devices available and add the appropriate etherguid to the prefs. That way two Basilisk/SheepShaver instances could be networked over the bridge. Assuming they both use a different tap device ;-) 

EDIT: I retract this request, it seems this functionality is already available ;-) It was just my 2nd tap device installation that was faulty.

Best,
Howard

**Comment by rakslice** [comment]
I'm curious, do you know what was faulty about the tap device installation that caused it to not be detected?

**Comment by cat7** [comment]
I'm not quite sure: earlier I had a tap device installed, but no openvpn parts. 
I installed a second tap device by going through device manager/add new device and then pointed to the driver C:\Program Files\TAP-Windows\driver\OemVista.inf. I think it was this device that was not recognised in the GUIs.

Reinstalling the minimal tap device from the openvpn download (2.4.9) (which always includes  openvpn user space components) gave me a tool C:\Program Files\TAP-Windows\bin\addtap.bat which did the job correctly.
