### ISSUE TITLE
Suggestion:  enable "ignore illegal memory access" and disable JIT compiler by default

### ISSUE THREAD

**Issue by watchsmart** [kanjitalk755/macemu#60]
I think it could be beneficial to have  "ignore illegal memory access" enabled and to have the JIT compiler disabled by default in the GUI when the emulator.   These settings would likely increase stability.  They are steps that new users are generally advised to take when setting up the emulator anyways.

A bit of discussion on this has happened over here - https://emaculation.com/forum/viewtopic.php?f=6&t=10847&p=68117

**Comment by rakslice** [comment]
Judging by the discussion, you mean this recommendation to be specific to Basilisk II?

**Comment by watchsmart** [comment]
"Ignore Illegal Memory Accesses" should be enabled in both Basilisk II and SheepShaver.

For now, I think the JIT compiler should be disabled for Basilisk II.  I guess more discussion is needed regarding SheepShaver.

**Comment by kanjitalk755** [comment]
I agree to turn on both BII and SS `ignoresegv` by default.

BII's JIT compiler is a little unstable, and even if it is off, it can get faster than the actual machine, so I think that off is good by default.

On the other hand, SS's JIT compiler is stable and the actual machine is fast, so I think it's better to turn it on.

**Comment by rakslice** [comment]
I agree with what @kanjitalk755 said there.

Is it sufficient to build the BII JIT by default and disable it by pref by default? This would be convenient for users who want to enable it in that they don't need a different build.

I think devs making code changes should run with `ignoresegv` to be aware of any new invalid memory accesses they create as a result of their changes breaking things, but to be blunt that's not guarantee they'll fix anything, and provided the option is still there for them and anyone who prefers [fail-fast](https://en.wikipedia.org/wiki/Fail-fast) generally to turn off, that is enough.

**Comment by kanjitalk755** [comment]
> Is it sufficient to build the BII JIT by default and disable it by pref by default?

Yes, the current code is stable enough if we build it with `USE_JIT` defined and set `jit false`.

**Comment by watchsmart** [comment]
Yes, my suggestions are only related to the default settings in the GUI.

**Comment by kanjitalk755** [comment]
Changed as mentioned above.
