### ISSUE TITLE
SheepShaver On Linux Seems to Need To Treat Caps Lock Key Events Like It Does On Windows

### ISSUE THREAD

**Issue by BloodyMess** [kanjitalk755/macemu#73]
My system config is this:

**SOFTWARE:**
- elementary OS 5.1.7 Hera (with all current updates) based on Ubuntu 18.04LTS
- Linux Kernel 5.4.0-58-generic
- GTK 3.22.30
- SheepShaver built from a current snapshot of master branch from this repository.

**HARDWARE:**
- Ryzen 3900X
- Radeon RX590
- 128GB RAM
- Matias Tactile Pro Keyboard for Mac

**PROBLEM:**
I recently noticed that the state of my caps lock key is being ignored when running SheepShaver on Linux. On further investigation, I discovered that the caps lock key had to be physically held down to get all caps, and as soon as I released it typing returned to lower case, effectively turning Caps Lock into an extra Shift key.

**INVESTIGATION:**
With this in mind, I took another look at the keyboard event handling in `handle_events()` in `video_sdl2.cpp` and noticed that the version for windows handles key up and key down caps lock events differently. To see what would happen, I changed the code that handles key up and key down events so that it always handles caps lock the way it does for windows.

This fixed the problem and I now have the caps lock key working as expected.

**SOLUTIONS:**
So it looks like SheepShaver needs to either have the Linux build handle caps lock press/release events the way they are on windows. Or... Possibly refine the keyboard options to let the user choose how caps lock should be handled?

I've been looking for documentation on changing the keyboard type code in the SheepShaver prefs file in case there's an existing workaround that I'm just not aware of. But I'm not having any luck with that so far.

**Comment by kanjitalk755** [comment]
> This fixed the problem and I now have the caps lock key working as expected.

Could you make a pull request of that fix?

**Comment by BloodyMess** [comment]
I've never done one before. But I don't mind trying. How do I go about making one?

**Comment by BloodyMess** [comment]
Does anyone know what the real life model number is for the keyboard that SheepShaver emulates when `keyboardtype 5` is used in the SheepShaver prefs?

I'm curious about how the keyboard type code in the prefs affects the processing of keyboard events, whether in SheepShaver, or in Mac OS itself.

My thinking is: *Maybe* Mac OS is expecting the keyboard with that id code to handle everything regarding caps lock state itself and just report the shift key being down as long as the caps lock is on? Maybe the keyboard with that code has a physical or electronic latch?

Maybe using a different keyboardtype prefs value would cause Mac OS to not make such an assumption (if it does at all), and handle non-Apple/ADB keyboards correctly?

**Comment by kanjitalk755** [comment]
> I've never done one before. But I don't mind trying. How do I go about making one?

See:
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

> Does anyone know what the real life model number is for the keyboard that SheepShaver emulates when keyboardtype 5 is used in the SheepShaver prefs?

For SheepShaver specifications, you may be able to get answers by asking questions at:
https://www.emaculation.com/forum/

**Comment by BloodyMess** [comment]
> > This fixed the problem and I now have the caps lock key working as expected.
> 
> Could you make a pull request of that fix?

OK. I think I got the pull request created.

**Comment by BloodyMess** [comment]
Your latest commit seems to fix it on Linux.
