### ISSUE TITLE
BasiliskII macOS messed up 'thousands' colors

### ISSUE THREAD

**Issue by RonaldPR** [kanjitalk755/macemu#75]
Yesterday I built both SheepShaver and BasiliskII with Xcode 12.4 in macOS 10.15.7. In BasiliskII the colors appear completely messed up when the Monitors control panel is set to thousands of colors. The issue is not in other color settings, it is only in BasiliskII, not in SheepShaver, and it is not in my 22 September 2020 BasiliskII build.

**Comment by kanjitalk755** [comment]
Fixed.
