### ISSUE TITLE
What is "swap_opt_cmd false"?

### ISSUE THREAD

**Issue by RonaldPR** [kanjitalk755/macemu#79]
While testing a new SheepShaver for macOS build, I noticed a new(?) line "swap_opt_cmd false" in the prefs file.
What is it?

**Comment by RonaldPR** [comment]
Oh, I see. Swapping option and command key if true. Not sure why or when that would be useful, though.

**Comment by RonaldPR** [comment]
Also does not work.

**Comment by RonaldPR** [comment]
Sorry. It does work, but only when keycodes is not used.

**Comment by kanjitalk755** [comment]
Fixed.
See #59 for the circumstances.
