### ISSUE TITLE
SheepShaver for macOS: "Basilisk II" in SheepShaver title bar when launched fullscreen

### ISSUE THREAD

**Issue by RonaldPR** [kanjitalk755/macemu#81]
When SheepShaver is launched fullscreen, the window title bar will appear for a split second. Confusingly the title is "Basilisk II".

In window mode and when using Control-Return to switch from window mode to full screen mode, the title in the title bar is correctly "SheepShaver".

**Comment by kanjitalk755** [comment]
Fixed.
