### ISSUE TITLE
SDL1 build?

### ISSUE THREAD

**Issue by almeath** [kanjitalk755/macemu#82]
I reported an issue on the Emaculation forums where the SDL2 builds of SheepShaver are causing some odd behavior with jumping title bars when launching in full screen mode. I was told that this is an inherent issue for SDL2 and there is currently no known work around. 

I was wondering if there is an option, perhaps a prefix for the make command, that will allow an SDL1 build of SheepShaver from current source? Or is that just not possible given the overall advances in the codebase?

**Comment by kanjitalk755** [comment]
This fork does not support to build with SDL1.
Even if you can switch back to SDL1, you will not be able to zoom in in full screen mode, only a small display in the center of the screen.

**Comment by almeath** [comment]
Thanks for the clarification.
