### ISSUE TITLE
unable to build audio_sdl.cpp - unknown dependency?

### ISSUE THREAD

**Issue by Zamlet** [kanjitalk755/macemu#83]
I am trying to build SheepShaver on my computer running Linux Mint 19.3 from a clone of the source made on 15-Feb-2021.  I followed the [Linux build instructions here](https://www.emaculation.com/doku.php/compiling_sheepshaver_basilisk).  No errors were reported until the final make (I never got to the strip command).  It also seemed to go well until it hit the file ../SDL/audio_sdl.cpp, at which point I received the following error:
```
g++ -DBINCUE  -I../kpx_cpu/include -I../kpx_cpu/src -DUSE_JIT -I../include -I. -I../CrossPlatform -I../slirp -DHAVE_CONFIG_H -D_REENTRANT -DDATADIR=\"/usr/local/share/SheepShaver\" -g -O2 -I/usr/include/SDL2 -D_REENTRANT  -c ../SDL/audio_sdl.cpp -o obj/audio_sdl.o
../SDL/audio_sdl.cpp: In function ‘int play_startup(void*)’:
../SDL/audio_sdl.cpp:372:95: sorry, unimplemented: non-trivial designated initializers not supported
  desired = { .freq = 44100, .format = AUDIO_S16, .channels = 1, .samples= 4096 }, obtained;
                                                                                ^
Makefile:197: recipe for target 'obj/audio_sdl.o' failed
make: *** [obj/audio_sdl.o] Error 1

```
I'm no expert, but this looks like it might be some sort of unsatisfied dependency.  I was unable to find a list of dependencies for pre-install.  Additional information will be provided on request as soon as someone tells me what is needed and how to get it!

**Comment by kanjitalk755** [comment]
Fixed.
