### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by Jagmn** [kanjitalk755/macemu#84]
Hi,

I've managed to build SDL2 and SheepShaver for Apple Silicon in Xcode. I just had to re-add 'arm64' to VALID_ARCH. Unfortunately I've not been able to get it running successfully.

1. The -pagezero_size linker option seems to produce binaries that segfault immediately. I used Unix/Darwin/testlmem.sh to experiment and I think this option just won't work for aarch64 - but I am willing for my opinion to be corrected!

2. Trying to get SheepShaver running without -pagezero_size always results in "**ERROR: Cannot map first Kernel Data area: Cannot allocate memory.**". I tried adding some extra _#ifdef (__aarch64__)_ where there was code to use **gZeroPage** and **gKernelData** but I then ended up with segfaults in the Mach message / segfault handler (accessing **ppc_cpu** before it was initialised).

So, really, I'm shooting in the dark as my knowledge of SS and PPC emulation is rather limited. Happy to help in any way to progress this, though. 

I've been working with master/4cf65a3faf22babd5aa403b02d33ce1c7e5f324c. Thanks

Macbook Air, M1,
Big Sur 11.2
Xcode 12.4

**Comment by kanjitalk755** [comment]
I don't have an M1 Mac.
If I buy it, I'll try to solve this issue.

**Comment by kanjitalk755** [comment]
I merged your patch which is posted to Emaculation forum.
BII/SS run well on the arm64.
