### ISSUE TITLE
Port RickyZhang's 24-bit patches?

### ISSUE THREAD

**Issue by adespoton** [kanjitalk755/macemu#87]
https://github.com/rickyzhang82/macemu/commit/342fbbce34d134a31382ca66c5ddd50590ae5904

I don't think there's anything there that should break in this version, and it does two things: it re-enables System 6 support in SDL2 BII, and it incorporates Paul's Mini vMac display handling, which unbinds the display from the emulator memory, fixing a few BII performance issues related to non-standard display resolutions.

**Comment by kanjitalk755** [comment]
See #85.
I'll merge if these issues are resolved.
