### ISSUE TITLE
SheepShaver for OSX/macOS:  Chinese file names in shared folder are not displayed correctly in "Unix"

### ISSUE THREAD

**Issue by RonaldPR** [kanjitalk755/macemu#89]
The discussion about this issue in emaculation forum is very confusing, but I think my summery here is clear: https://www.emaculation.com/forum/viewtopic.php?p=70332#p70332

**Comment by kanjitalk755** [comment]
The file name encoding is different between macOS and (classic) MacOS.
SheepShaver does not convert the encoding, so it is a specification at present.

**Comment by RonaldPR** [comment]
If that is so, how is it then possible that when files are copied in OSX/macOS to a HFS+ disk image and that image is mounted in SheepShaver (added to the volumes list), the Chinese file names still appear correctly in (classic) MacOS. The same files do not show the correct file names in "Unix" when added to the shared folder.

**Comment by RonaldPR** [comment]
The issue is with classic MacOS files. The files still show correct file names in OSX/macOS, but not when "Unix" is used to copy them back to a Chinese MacOS guest system in SheepShaver.

**Comment by kanjitalk755** [comment]
> If that is so, how is it then possible that when files are copied in OSX/macOS to a HFS+ disk image and that image is mounted in SheepShaver (added to the volumes list), the Chinese file names still appear correctly in (classic) MacOS.

I tested a file which name is Japanese, it appeared incorrect in SheepShaver.

**Comment by RonaldPR** [comment]
Was it a classic Mac OS Japanese file, one created in for instance MacOS9?

The person who reported this issue can see correct Chinese file names of classic Mac OS Chinese files in both OSX and in MacOS in SheepShaver when the file is on a HFS+ disk image. Could OSX be backward compatible with classic Mac OS file names?

See this forum post: https://www.emaculation.com/forum/viewtopic.php?p=70244#p70244

**Comment by kanjitalk755** [comment]
> Was it a classic Mac OS Japanese file, one created in for instance MacOS9?

I tested:
copy a macOS file to HFS+ disk image -> show in SheepShaver ... no good

And just now tested:
copy a MacOS 8 file to HFS+ disk image in SheepShaver -> show in macOS ... OK

I'm not sure about the specifications.

> Could OSX be backward compatible with classic Mac OS file names?

I couldn't find any documents about compatibility of the encoding.

**Comment by RonaldPR** [comment]
Interesting. So the observations of the person who complained about incorrect display of multibyte characters in file names in "Unix" are correct.

He (or she) works with classic MacOS files, can see the correct names of those files in MacOS in SheepShaver **and** in OSX/macOS, but if the file is in the shared folder, the file name is displayed 'garbled' in "Unix".

Can you find any documentation about the encoding used in classic MacOS? I have a vague recollection about UTF-8 encoding being introduced in MacOS 8, but I cannot find any reference to that.

**Comment by RonaldPR** [comment]
Another observation by the person who reported the issue:

When he uses SheepShaver with Chinese MacOS in Windows 7, and accesses the disk with the classic MacOS files through the 'My Computer' icon, the files are unusable because, as expected, all file attributes are lost, but the file names appear intact in SheepShaver.

(I just now learned that he uses Simplified Chinese.)

**Comment by kanjitalk755** [comment]
I have implemented prefs item `name_encoding`.
For example, if you add `name_encoding sjis` to the prefs file, Japanese file names will be displayed correctly.
If not specified, it is the same `MacRoman` as before.
You can use one of the keywords displayed by `iconv -l` on the command line.
Depending on the type of OS / Language Kit, you will not know which one is appropriate until you try it.

**Comment by RonaldPR** [comment]
I will try that, or rather I will suggest the Chinese user to try it with a new build.

I suppose it works in both SheepShaver and BasiliskII, right?
Does it affect only SheepShaver and BasiliskII for macOS?

I suppose the keywords to try with Simplified Chinese are:
CHINESE GB_2312-80 ISO-IR-58 CSISO58GB231280
CN-GB-ISOIR165 ISO-IR-165

Seeing that you use "sjis" for Japanese, I suppose the keywords are not case-sensitive.

**Comment by RonaldPR** [comment]
Emaculation forum member "adespoton" thinks there is a different solution, see: https://www.emaculation.com/forum/viewtopic.php?f=20&p=70369#p70369

Maybe you can comment on it.

**Comment by RonaldPR** [comment]
I wonder:

The file name encoding that is used should be the file name encoding that is used in the classic MacOS version that is installed in SheepShaver (or BasiliskII).

Is there no way for SS or BII to find which encoding that is? For instance when an example file is copied inside  SS or BII  to "Unix"?

**Comment by kanjitalk755** [comment]
If you have a database of files that are always installed and have different names for each language,
SheepShaver may be able to detect it when you copy the file to "Unix".

**Comment by RonaldPR** [comment]
Could be one of the applications in the Apple menu, I suppose.

Maybe a project for later. So far I heard of only one user complaining about the wrong file names.
We will try the "name_encoding" prefs item for now.

**Comment by largefield-ohara** [comment]
I've been using Japanese for a long time on "UNIX" on OS X. To do so, it was sufficient to modify the previous version extfs_macosx.cpp by three lines.

First, include CFStringEncodingExt.h.
Next, Just change the argument "kCFStringEncodingMacRoman" of convert_string() to "kCFStringEncodingMacJapanese" in host_encoding_to_macroman() and macroman_to_host_encoding().
That's it.

If you change "kCFSStringEncodingMacJapanese" to "kCFStringEncodingMacChineseTrad" or "kCFStringEncodingMacChineseSimp", it will be displayed in Chinese even on "UNIX". I think.

**Comment by kanjitalk755** [comment]
@largefield-ohara
Thank you for the information.
Reverted to the implementation using Core Foundation.

@RonaldPR
Changed the notation of `name_encoding`.
For example:
`name_encoding 1` for Japanese
`name_encoding 2` for Chinese

**Comment by RonaldPR** [comment]
I will make new test builds.

Which one (2 or 25) is Chinese Simplified and which one is Chinese Traditional?

**Comment by largefield-ohara** [comment]
@kanjitalk755
I think it would be useful to have a language selection menu in the preferences so that users can choose their language.

@RonaldPR
2 is in traditional Chinese(CFStringEncodingMacChineseTrad) and 25 is in simplified Chinese(kCFStringEncodingMacChineseSimp).

**Comment by kanjitalk755** [comment]
> I think it would be useful to have a language selection menu in the preferences so that users can choose their language.

Yes, but I'm not interested in the GUI and will not implement it.
Of Course, a pull request is welcome.

**Comment by RonaldPR** [comment]
It would be useful if most of the (by now 12) new features could be set in the GUI preferences (as opposed to adding them manually to the prefs file). If anyone would be interested to work on the GUI, I can test and comment on beta versions, as I have been doing, and still do, for the BasiliskII GUI.

**Comment by largefield-ohara** [comment]
I've been away from GUI programming on mac for quite some time now, so I have no idea what the current methods are... At best, I only know GUIs from the System 7 era.

**Comment by RonaldPR** [comment]
I am waiting for the Chinese user to report that this works for him.

In the meantime:
Is this implemented only for Japanese and Chinese (Trad and Simp) or will it now work for other non-MacRoman languages also? For instance:

`name_encoding 6` for Greek
`name_encoding 7` for Cyrillic

**Comment by kanjitalk755** [comment]
Probably works.
The list of values ​​is described in the following file.

/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStringEncodingExt.h

**Comment by RonaldPR** [comment]
There is no /Library/Developer/CommandLineTools/ folder on my Mac, also no ~/Library/Developer/CommandLineTools/ folder.

**Comment by RonaldPR** [comment]
I found the file on he web.

**Comment by RonaldPR** [comment]
A bit off-topic:
I always assumed that the Command Line Tools were installed with or by Xcode. Apparently not. Haven't used any for a long time, so I did not notice that they were missing.

**Comment by RonaldPR** [comment]
The user who originally reported Chinese characters not being displayed correctly in "Unix" confirmed that "name_encoding" works for him as intended.
