### ISSUE TITLE
/slirp/version:1:1: Unknown type name 'qemu'

### ISSUE THREAD

**Issue by thePublicer** [kanjitalk755/macemu#90]
/slirp/version:1:1: Unknown type name 'qemu'

**Comment by kanjitalk755** [comment]
Could you explain detail of the issue?

**Comment by thePublicer** [comment]
it file when it build the xcode version
<img width="1403" alt="Screen Shot 2021-04-29 at 3 22 47 PM" src="https://user-images.githubusercontent.com/50846515/116606529-dc881f00-a8fe-11eb-90bd-a71e0759dcb3.png">

**Comment by thePublicer** [comment]
It Fail the Build, here the screenshot:
<img width="1403" alt="Screen Shot 2021-04-29 at 3 22 47 PM" src="https://user-images.githubusercontent.com/50846515/116606768-31c43080-a8ff-11eb-8957-7834d9285e30.png">

**Comment by thePublicer** [comment]
[errno.txt](https://github.com/kanjitalk755/macemu/files/6401694/errno.txt)

**Comment by thePublicer** [comment]
[errno.log](https://github.com/kanjitalk755/macemu/files/6401696/errno.log)

**Comment by thePublicer** [comment]
[xcodebuildfailure.txt](https://github.com/kanjitalk755/macemu/files/6401697/xcodebuildfailure.txt)

**Comment by thePublicer** [comment]
thanks
