### ISSUE TITLE
BasiliskII buidling error: 'mpfr.h' file not found

### ISSUE THREAD

**Issue by RonaldPR** [kanjitalk755/macemu#93]
I tried to build BasiliskII on my new M1 iMac.

I installed mpfr as instructed. Still, building BasiliskII fails with this error:

'mpfr.h' file not found
types.h
In file included from /Users/ronald/Desktop/macemu-master/BasiliskII/src/uae_cpu_2021/newcpu.cpp:47:
In file included from ../uae_cpu_2021/fpu/fpu.h:51:

When I try to install mpfr again, I get:
mpfr 4.1.0 is already installed and up-to-date

Searching my disk I find:
mpfr.h and mpf2mpfr.h (files) in: usr/local/Cellar/mpfr/4.1.0/include
mpfr.h and mpf2mpfr.h (aliases) in: usr/local/include

**Comment by kanjitalk755** [comment]
It seems that the libraries installed in /usr/local is for Intel.
For ARM those will be installed in /opt/homebrew.

**Comment by RonaldPR** [comment]
I have two Homebrew folders: /usr/local/Homebrew/ and /opt/homebrew/

When I install mpfr, it is always again installed in the locations in /usr/local/ I mentioned above.
Also after first removing the installed mpfr and also with` $ brew reinstall mpfr`

Terminal is not set to run with Rosetta.

When I remove  /usr/local/Homebrew/ the command "brew" is not available.

**Comment by RonaldPR** [comment]
/opt/homebrew/bin/brew is available but ,apparently, Terminal insists on using /usr/local/Homebrew/bin/brew

**Comment by RonaldPR** [comment]
Last login: Sun Jun 13 09:24:31 on ttys000
ronald@MacKanjer6 ~ % brew install mpfr
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
elfutils        maturin         moar            slides          tmuxp
==> Updated Formulae
Updated 183 formulae.

==> Downloading https://ghcr.io/v2/homebrew/core/mpfr/manifests/4.1.0
Already downloaded: /Users/ronald/Library/Caches/Homebrew/downloads/e8b18e060649c00d9e1e351e3e05515c365e52dbd7bd392e2b99808d1f355b5b--mpfr-4.1.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/mpfr/blobs/sha256:1e8eb0326f62d
Already downloaded: /Users/ronald/Library/Caches/Homebrew/downloads/c0fa3566c6af3a4fefde940e344c5d184dde4c60263158a9cc4c13602bda99a5--mpfr--4.1.0.big_sur.bottle.tar.gz
==> Pouring mpfr--4.1.0.big_sur.bottle.tar.gz
Warning: This keg was marked linked already, continuing anyway
🍺  /usr/local/Cellar/mpfr/4.1.0: 30 files, 5.2MB
ronald@MacKanjer6 ~ %

**Comment by kanjitalk755** [comment]
> /opt/homebrew/bin/brew is available but ,apparently, Terminal insists on using /usr/local/Homebrew/bin/brew

You need to add /opt/homebrew/bin to head of your PATH.

**Comment by RonaldPR** [comment]
Yes, of course. That worked to install mpfr in /opt/homebrew

I will again try and build BasiliskII (and SheepShaver) later this week.

**Comment by RonaldPR** [comment]
BasiliskII builds fine now, but will start a thread for a different issue.
