### ISSUE TITLE
keycodes for SDL2 Linux/X11

### ISSUE THREAD

**Issue by RonaldPR** [kanjitalk755/macemu#95]
Questions rather that an issue:

1. What is the header needed for SDL2 Linux/X11 builds to use SDL2 scancodes to Mac keycodes translations in keycodes files? (Like "sdl cocoa" for macOS and "sdl windows" for Windows).

2. Will that header work only for your SDL2 port or will it also work for SDL2 ports from other branches?

**Comment by kanjitalk755** [comment]
> What is the header needed for SDL2 Linux/X11 builds to use SDL2 scancodes to Mac keycodes translations in keycodes files? (Like "sdl cocoa" for macOS and "sdl windows" for Windows).

It is `sdl x11`.

> Will that header work only for your SDL2 port or will it also work for SDL2 ports from other branches?

It works if `keycode_init()` in `video_sdl2.cpp` is same as this fork.
Otherwise, it may not work.

**Comment by RonaldPR** [comment]
That header was already in use before SDL2:

```
#
# X11 server
# X.Org
#
sdl x11
sdl dga
The X.Org Foundation
9	53	# Esc
67	122	# F1
68	120	# F2
69	99	# F3
70	118	# F4
71	96	# F5
72	97	# F6
73	98	# F7
74	100	# F8
75	101	# F9
76	109	# F10
95	103	# F11
96	111	# F12
111	105	# PrintScrn
78	107	# Scroll Lock
110	113	# Pause
49	50	# `
10	18	# 1
11	19	# 2
12	20	# 3
13	21	# 4
14	23	# 5
15	22	# 6
16	26	# 7
17	28	# 8
18	25	# 9
19	29	# 0
20	27	# -
21	24	# =
22	51	# Backspace
106	114	# Insert
97	115	# Home
99	116	# Page Up
77	71	# Num Lock
112	75	# KP /
63	67	# KP *
82	78	# KP -
23	48	# Tab
24	12	# Q
25	13	# W
26	14	# E
27	15	# R
28	17	# T
29	16	# Y
30	32	# U
31	34	# I
32	31	# O
33	35	# P
34	33	# [
35	30	# ]
36	36	# Return
107	117	# Delete
103	119	# End
105	121	# Page Down
79	89	# KP 7
80	91	# KP 8
81	92	# KP 9
86	69	# KP +
66	57	# Caps Lock
38	0	# A
39	1	# S
40	2	# D
41	3	# F
42	5	# G
43	4	# H
44	38	# J
45	40	# K
46	37	# L
47	41	# ;
48	39	# '
83	86	# KP 4
84	87	# KP 5
85	88	# KP 6
50	56	# Shift Left
94	50	# International
52	6	# Z
53	7	# X
54	8	# C
55	9	# V
56	11	# B
57	45	# N
58	46	# M
59	43	# ,
60	47	# .
61	44	# /
62	56	# Shift Right
51	42	# \
98	62	# Cursor Up
87	83	# KP 1
88	84	# KP 2
89	85	# KP 3
108	76	# KP Enter
37	54	# Ctrl Left
115	58	# Logo Left (-> Option)
64	55	# Alt Left (-> Command)
65	49	# Space
113	55	# Alt Right (-> Command)
116	58	# Logo Right (-> Option)
117	50	# Menu (-> International)
109	54	# Ctrl Right
100	59	# Cursor Left
104	61	# Cursor Down
102	60	# Cursor Right
90	82	# KP 0
91	65	# KP .
```

**Comment by kanjitalk755** [comment]
Yes, `x11` is the video driver name returned by SDL, it has been used since SDL 1.x.

**Comment by RonaldPR** [comment]
So far, I made the keycodes files to be compatible with all current and previous BasiliskII and SheepShaver builds. That was possible because `sdl cocoa` for macOS and `sdl windows` for Windows were new to be added for the SDL2 builds. Before that `sdl windib` and `sdl directx` were used for windows and `sdl Quartz` was used for OSX.

I will remove the existing `sdl x11` header from the older (SDL1) Linux/X11 translations in the keycodes files. Then translations from SDL2 scancodes can be made available for Linux/X11.
