### ISSUE TITLE
SheepShaver for macOS thousands of colors issue

### ISSUE THREAD

**Issue by RonaldPR** [kanjitalk755/macemu#98]
Recent SheepShaver for macOS on Intel has an issue when set to thousands of colors. The colors appear completely off.

It does not affect:
17 March 2021 Intel build

It does affect:
21 April 2021 Intel build
28 April and 14 June universal builds when forced to run with Rosetta2

I also tried BasiliskII.
The issue does not affect the 28 April and 14 June universal builds when run with Rosetta2.
(The intel builds refuse to run on my M1 iMac, despite Rosetta2 being installed.)

**Comment by kanjitalk755** [comment]
Fixed.

**Comment by RonaldPR** [comment]
That is quick! :)
