### ISSUE TITLE
Entry point not found

### ISSUE THREAD

**Issue by Neelix57** [kanjitalk755/macemu#99]
I compiled the latest version of BasiliskII and SheepShever for Windows on 32 bit Windows 7, following this tutorial:
[https://www.emaculation.com/doku.php/compiling_sheepshaver_basilisk](https://www.emaculation.com/doku.php/compiling_sheepshaver_basilisk)

I'm unable to launch BasiliskIIGUI as well as SheepShaverGUI. Both give me the error:

`The procedure entry point _ZdaPv could not be located in the dynamic link library libharfbuzz-0.dll`

GTK+ 2.10.13 as well as SDL 1.2.13 and Harfbuzz 2.8.2 are installed.

Could someone help please ?

**Comment by kanjitalk755** [comment]
It's weird. BII and SS don't use libharfbuzz.
Install SDL 2 (not SDL 1.2) and try again.

**Comment by Neelix57** [comment]
It's the same with SDL2.

**Comment by kanjitalk755** [comment]
Could you upload the logs of `configure` and `make`?

**Comment by Neelix57** [comment]
Where do I find the logs ?

**Comment by kanjitalk755** [comment]
Save the logs as follows.

```
$ cd macemu/BasiliskII/src/Windows
$ ./configure >configure_log.txt 2>&1
$ make clean
$ make >make_log.txt 2>&1
```

**Comment by Neelix57** [comment]
Here are the logs.
Thank you for spending time to help.

[configure_log.txt](https://github.com/kanjitalk755/macemu/files/6848388/configure_log.txt)
[make_log.txt](https://github.com/kanjitalk755/macemu/files/6848389/make_log.txt)

**Comment by kanjitalk755** [comment]
According to configure_log.txt, GTK+ was not detected.
And according to make_log.txt, BasiliskIIGUI.exe was not built due to lack of GTK+.
It is believed that the BasiliskIIGUI.exe you ran was not a build from this fork.

Install GTK+ and try again.

**Comment by Neelix57** [comment]
As said above, GTK+ 2 is installed. I reinstalled it, but ./configure sais always 

`checking for GTK+ - version >= 1.3.15... no`
`GTK user interface ..................... : no`

**Comment by kanjitalk755** [comment]
By the way, do you need to build BasiliskIIGUI.exe and SheepShaverGUI.exe?
If you just want to use them, you can download them from https://emaculation.com/forum.
The download files also contain the required DLLs.

**Comment by Neelix57** [comment]
I would build an updated version.

**Comment by RonaldPR** [comment]
The latest BasiliskII for Windows build posted in emaculation forum is from 29 May 2021. Any specific change since that date you need? If so, you can ask in the forum for a newer build.

**Comment by kanjitalk755** [comment]
> I would build an updated version.

BasiliskIIGUI.exe and SheepShaverGUI.exe built from the latest sources are the same as those that can be downloaded from the Emaculation forum.

Looking at the logs, the latest version of BasiliskII.exe was built correctly.
Probably SheepShaver.exe as well.
